### ISSUE TITLE
Mahdollisuus TILITYS -kirjauksiin "Muu" -tositteella

### ISSUE THREAD

**Issue by NikoGrano** [artoh/kitupiikki#1017]
Onko mahdollista mahdollistaa 901, eli Tilitys ALV merkinnät "Muu" -tositteiden rivellä.

https://github.com/artoh/kitupiikki/blob/5d129614e962237799ee8021d1ce0bd0c72dacfc/kitsas/db/verotyyppimodel.h#L53

**Comment by artoh** [comment]
Lisätty mahdollisuus myös Tekninen kirjaus -verotyyppiin tässä muokkausnäkymässä
