### ISSUE TITLE
PDF-esikatselu ei aina toimi "pakatuille" tiedostoille

### ISSUE THREAD

**Issue by jpink** [artoh/kitupiikki#1032]
Pienennän PDF-tiedostot ennen tositteeseen liittämistä, jotta ne eivät veisi ylimääräistä tilaa tietokannasta ja arkistosta.

Valtaosa (ei kaikki) pienentämistäni tiedostoista näkyy pelkkänä mustana 2x2px pisteenä esikatselussa. Kitsas kuitenkin lukee kentät PDF:stä oikein. Ja jos liitteen avaa esim. selaimessa, niin se näkyy oikein.

PDF-tiedoston voi pienentää esim. [Online2PDF](https://online2pdf.com/pdf-change-color-to-black-and-white) -palvelussa. Käytän seuraavia valintoja:

- **Quality of images**: `1 - low quality`
- **Resolution of images**: `25 dpi (lowest resolution)`
- **Color / black-and-white**: `Black-and-White (gray scale)`

Lopputuloksena on n. 5 kertaa pienempi tiedosto (450 kt -> 80 kt).

**Comment by helihyv** [comment]
En saanut ongelmaa toistettua noilla asetuksilla pienennetyllä tiedostolla. Voisitko liittää tänne jonkin pdf-tiedoston, jolla vika ilmenee?

**Comment by jpink** [comment]
Nyt kun kokeilin uudestaan, niin en saanut toistettua minäkään. Varmaan ongelma korjaantui kun käynnisti Kitsaan uudelleen. Suljen tämän ja avaan jos saan taas ilmenee.
