### ISSUE TITLE
Toimittajien lisäys ei toimi

### ISSUE THREAD

**Issue by arihannu** [artoh/kitupiikki#1033]
Käytössä Kitsas 2.3, MacOS 11.4

Kun yritän lisätä uuden toimittajan (Laskut -> Toimittajat | Uusi), ja annan vain uuden nimen, toimittajaa ei lisätä listalle. Samoin jos kululaskun kirjauksessa laitan uuden laskuttajan nimen, toimittajaa ei näy Toimittajat listalla.

**Comment by artoh** [comment]
Toimittajalistalle pääsee vasta kun ko. kumppanille on kirjattu ostolaskuja, asiakasrekisterille kun on myyntilaskuja (ennen sitä näkyy vain Rekisteri-välilehdellä). Tältä osilta selkeytetään käyttöliittymää kolmosversiossa.
