### ISSUE TITLE
Arvonlisäverolaskelma, alarajahuojennus

### ISSUE THREAD

**Issue by PetriRa** [artoh/kitupiikki#1049]
Kitsas 2.3, pilvi.

Tein just tilikauteni viimeisen alv-ilmoituksen, kuva. 
Yllätys oli että tässä näkyi Alarajahuojennukseen liittyviä tietoja erittelyssä. Ilmeisesti suunnitellusti, kun kyse on tilikauden viimeisestä kaudesta. 

Rajat mulla paukkuu reippaasti, joten en tietenkään noita omaveroon naputtele. Mutta kitsaan laskelma kyllä siihen hieman houkuttaa, ja joku saattaisi siihenkin haksahtaa. 
Mielestäni kannattaisi muuttaa hieman, että käy ilmi ettei näitä tule ilmoittaa, kun rajat menee yli. Esim:

_315 Alarajahuojennukseen oikeuttava liikevaihto 387 288,06
316 Alarajahuojennukseen oikeuttava vero 33 052,76_
Ei oikeutta alarajahuojennukseen, liikevaihtoraja 30000 ylittyy.

315 Alarajahuojennukseen oikeuttava liikevaihto 23 288,06
316 Alarajahuojennukseen oikeuttava vero 352,76
Oikeus alarajahuojennukseen, liikevaihtoraja 30000 ei ylity. 

![KitsasAlvLaskelma](https://user-images.githubusercontent.com/80963951/131213302-1b39b083-502d-4e59-ae76-608fe739c423.jpg)

**Comment by artoh** [comment]
Jos alarajahuojennusta on tulossa, tulee tuohon alle rivi 317 Alarajahuojennuksen määrä.

Listään inforivi siitä, jos huojennukseen ei ole oikeutta. Oikeastaan koko alarajahuojennusalueen voisi jättää silloin tulostamattakin, mutta ehkä etekin lähellä rajoja on ihan hyvä nähdä, että ohjelma on tutkinut asian.
