### ISSUE TITLE
Vanhan tositteen tiedot kaput

### ISSUE THREAD

**Issue by NikoGrano** [artoh/kitupiikki#1051]
3.0 päivitetty kirjanpito. Avaan tositteen, jossa on osto ulkomailta.

**Tosite**
![bug](https://user-images.githubusercontent.com/4658966/131619464-c5f9bb8e-a266-4716-aa66-9fbe2c701591.png)

**Viennit**
![bug2](https://user-images.githubusercontent.com/4658966/131619710-79e26d08-b8d1-4191-a236-ad113c4f0ce1.png)

Kun avaan saman kirjanpidon 2.3 kanssa, niin tuo tosite aukee oikein eli seuraavasti
**Tosite**

![2 3](https://user-images.githubusercontent.com/4658966/131620030-791c0115-2f73-4dc1-95b2-1381fee177a6.png)

**Comment by helihyv** [comment]
Alv-laji  näkyy näissä edelleen tyhjänä 3.0.1-betassa. Sitä ei myöskään pääse vaihtamaan, pudotusvalikkoa ei saa esiin.
