### ISSUE TITLE
Muokatun laskun tallentaminen (disable Tallenna valmiina)

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1085]
Jotta kirjanpidossa jo oleva lasku ei putoa pois kirjanpidosta, ei kirjanpidossa olevaa laskua muokattaessa saisi tallentaa sitä valmiina eli sijoittaa Lähetettävät-välilehdelle.

**Comment by helihyv** [comment]
Toimii.
Laskun voi kuitenkin yhä tallentaa luonnoksena, mikä myös poistaa sen kirjanpidosta.

**Comment by helihyv** [comment]
Myöskään valmiina tallennettua (lähettämätöntä, ei kirjanpidossa olevaa) laskua ei voi enää uudestaan tallentaa valmiina.
