### ISSUE TITLE
ALV-ilmoitinaineisto

### ISSUE THREAD

**Issue by PetriRa** [artoh/kitupiikki#1091]
Alv-ilmoitinaineisto, suuret kiitokset tuosta, helpottaa huomattavasti hommia ja vähentää virheitä. 

Hieman kaipaisi kuitenkin vielä viilaamista. 

Tallennushakemisto, pitäisi olla asetus, jossa määritellään mihin tuo tallennetaan. Nyt ehdottaa aina Kitsaan ohjelmahakemistoa, joka ei ole oikea paikka. 

Tiedoston nimi, nyt on aina ALV_VVVVKK.txt, lisää vaikka yrityksen nimi tuohon vielä, esim:
ALV_202110_YritysOy.txt
ALV_202110_KitsasOy.txt 
Kun tekee kirjanpitoa useammalle yritykselle, niin mielellään lähettää kaikki kerralla, samasta hakemistosta, ettei tarvitse miljoonaa kertaa hakata mobiilitunnuksia. Nyt pitää itse muutella tiedostonimeä ettei tallenna päälle.

**Comment by artoh** [comment]
Valittu hakemisto tallennetaan ja sitä ehdotetaan seuraavalla kerralla

**Comment by PetriRa** [comment]
Tämä ominaisuus on mennyt rikki, käsittääkseni 3.2.1 version myötä. Ehdottanut pitkin kesää taas tallennuspaikaksi ohjelmakansiota.
