### ISSUE TITLE
Toive, "ALV-maksulappu"

### ISSUE THREAD

**Issue by PetriRa** [artoh/kitupiikki#1092]
Eli kuinka kerron kirjanpitoasiakkaalleni, montako tonnia tällä kuulla lähettää alv-verottajalle.
 
Yksinkertaisimmillaan tuo nykyinen Arvonlisäverolaskelma, ilman Erittely-osiota. Kerron viestissä että ottaa summan kohdasta 308. 

Hieman paranneltuna lisättynä eräpäivällä, viitenumerolla, tilinumerolla ja summalla, paitsi jos summa miinuksilla, niin sitten vain huomautus ilman numeroita. 

Ja parhaimmillaan vielä pankkiviivakoodilla ja virtuaaliviivakoodilla täydennettynä. 

Esimerkiksi:

![alvmaksulappu](https://user-images.githubusercontent.com/80963951/137938306-75db2f2a-f417-4a83-a001-d60d4b27abc8.jpg)

**Comment by helihyv** [comment]
Toteutettu versioon 5.0
