### ISSUE TITLE
Tositteiden lisätiedot eri maksutavoilla

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1095]
Nykyisin laskujen lisätiedot ovat näkyvissä vain, kun tase-erittelynä on täysi tase-erittely tai tase-erien luettelo.
Laskujen lisätiedot voitaisiin liittää suoraan tiettyihin maksutapoihin.
Samoin maksutapa voitaisiin tallentaa suoraan tositteelle (toistaiseksi liittyy laskun vastatiliin ja tase-eriin)

**Comment by helihyv** [comment]
Lisätietojen tason voi valita asetuksista
