### ISSUE TITLE
Tiliotteen kirjaamiseen kehitystä

### ISSUE THREAD

**Issue by jesseuitto** [artoh/kitupiikki#1103]
OP:n tiliotteissa on tullut jotain muutoksia arviolta syys-lokakuussa. Ennen muistaakseni Kitsas tunnisti viitteen perusteella maksetut laskut ja kirjasi ne oikein. Nyt ei taida mennä yhtäkään oikien, kaikki joutuu käsin täsmäyttämään avoimiin laskuihin. Usein vieläpä täsmäyttämiseen mennessä siinä saattaa olla vakiona jokin täysin turha hakuteksti, esim. "OKOYFIHH", jolla ei löyty yhtään laskua, joudun käsin poistamaan haun tai kirjoittamaan siihen toimittajan nimen.

Tapahtumat muutoinkin näyttää hassulta kun OP:n CSV:n tänne tuo, se oli muutamia kuukausia sitten hieman erinäköinen. Voin tarvittaessa toimittaa OP:n tiliotteen.

Nämä on pieniä asioita. Mutta ehkä isompi haaste on se, että kun Kitsas muutoin onnistuneesti tietää toimittajan perusteella mitä tilejä halutaan käyttää, niin tiliotteella on aina tietyt väärät tilit. Esimerkiksi menoja se haluaa toimittajan perusteella laittaa erilaisille kulutileille, kun nämä pitäisi kirjata 2871-ostovelkoihin. Sama tuloissa, ne tulisi kirjata 1701-tilille vakiona.

Voisiko näitä vakiotilejä jostain muokata? Nyt asetuksista löytyvä kohta listaa vain tulo/menotilit, ei tasetilejä, joille tiliotteen haluaisin kohdistaa. Toisekseen voisiko Kitsas tunnistaa toimittajan perusteella halutut tilit erilailla tositteita kirjatessa ja tiliotetta kirjatessa?

**Comment by artoh** [comment]
2e34ff4aed50f791c3289e7c8a8d606e14a49f4f
Mahdollisuus valita osto/myyntivelkatilit tiliotteen kirjauksen oletustileiksi Asetukset > Oletustilit
