### ISSUE TITLE
Liitteen lisäämisen jumittaa "Tallennetaan..."-ilmoitukseen

### ISSUE THREAD

**Issue by emilselroos** [artoh/kitupiikki#1104]
Yrittäessä lisätä liitettä tositteelle, ilmestyy tositteen tietojen alapuolelle keltaisella taustalla ilmoitus "Tallennetaan...", joka ei poistu odottamalla. Toiminnon voi peruuttaa, jolloin liite ei luonnollisesti näytä menneen läpi.

Tästä virheestä johtuen myöskään esimerkiksi ALV-kirjauksen tekeminen ei onnistu: ALV-ruutu jää "OK"-napin painamisen jälkeen päälle ja jos ruudun peruuttaa, tosite on kirjauksineen kyllä ilmestynyt kirjanpitoon, mutta siihen ei ole tallentunut PDF-tiedostoa eikä se siksi ole myöskään mennyt "läpi" eikä ilmesty ALV-listaukseen.

Samassa kirjanpidossa liitteiden lisääminen on aiemmin (3,75 vuoden ajan) toiminut ongelmitta.

Seuraava rivi löytyy virheenjäljitystiedoista:
`warning [ 500   "/liitteet/274/alv" ]  "database disk image is malformed Rivin noutaminen epäonnistui`

Ongelma johtunee siis omalla kohdalla korruptoituneesta tiedostosta tai tiedostoista, mutta jonkinlaisen virheenkäsittelyn ja -ilmoituksen lisääminen voisi helpottaa vastaavien ongelmatilanteiden löytämistä ja ratkomista.

**Comment by artoh** [comment]
Tässä on kirjanpitotiedosto päässyt ikävällä tavalla korruptoitumaan, joten oikein muu ei taida auttaa kuin ajantasainen varmuuskopiotiedosto.
Lisätty virhemessagebox myös liitteen tallennuksen yhteyteen.
