### ISSUE TITLE
Tilinavaus-ruksin poistaminen tilikaudesta ei poista tilinavausta, vaikka aukeava dialogi niin väittääkin

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#1110]
Joko tilinavauksen pitäisi poistua tai dialogin kehottaa poistamaan tai siirtämään tilinavaustosite. itse. Jälkimmäinen olisi ystävällisempää niitä kohtaan, jotka ovat tehneet tilinavauksen väärälle tilikaudelle.

**Comment by artoh** [comment]
Dialogin tekstiä muokattu
