### ISSUE TITLE
Arkisto-nappi ei muodosta arkistoa uudeleen vaikka raporttia on muokattu

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#1118]
Testtau taseella.
Tositteen muokkaamisen tai lisäämisen jälkeen arkiston saa muodostettua uudelleen ja muuttunut raportti näkyy.

**Comment by helihyv** [comment]
Havaittu sekä paikallisesti että pilbeen tallennetuissa kirjanpidoissa.

**Comment by artoh** [comment]
Ominaisuus ;)

Jos raporttien muokkaaminen tekisi kaikista vanhoista arkistoista kelvottomia, eivät vanhojen tilikausien arkistojen tarkastussummat säilyisi.
Tässä tilanteesa helpointa on poistaa kyseinen arkistohakemisto (tai sen index.html-tiedosto) jolloin täppä poistuu ja arkisto laaditaan uudelleen.
