### ISSUE TITLE
Matala kontrasti banneri-ilmoituksissa tummalla teemalla

### ISSUE THREAD

**Issue by samporapeli** [artoh/kitupiikki#1123]
Kun työpöytäympäristö on asetettu käyttämään tummaa teemaa (dark theme), Kitsaan banneri-ilmoituksissa on valkoista tekstiä vaaleanvihreällä pohjalla ja tekstin lukeminen on vaikeaa:
![image](https://user-images.githubusercontent.com/35733458/149654611-a3b0dd0c-8751-4bec-9e8f-7df25af51713.png)
Tämä tapahtuu ainakin Debian GNU/Linuxilla Plasma-työpöytäympäristössä (bspwm-ikkunamanagerilla). Kun järjestelmän vaihtaa vaaleaan teemaan ja Kitsaan käynnistää uudelleen, ilmoituksissa on kaikki kunnossa.

**Comment by artoh** [comment]
Määritelty musta/valkoinen väri tyylitiedostossa (tämä ei valitettavasti tue tummaa teemaa, mutta pitäsi olla luettavissa)
