### ISSUE TITLE
Tase-erittelyssä rivin selite haetaan väärältä tositteelta, jopa väärältä tilikaudelta

### ISSUE THREAD

**Issue by rjoonas** [artoh/kitupiikki#1140]
Moikka, alun perin Kitupiikillä laadittu kirjanpitoni tilikaudelle 2020 on mennyt jotenkin aivan solmuun tilikauden yli siirtyneiden tase-erien osalta sen jälkeen, kun olen tuonut kirjanpidon Kitsaaseen. Ihmettelin ensin, että kuinka on mahdollista, ettei lukitun tilikauden tulos enää täsmää viralliseen Kitupiikillä laadittuun tuloslaskelmaan. Sain sitten tilejä vertailemalla selville, että tilikauden aineisto poikkeaa muutaman tositteen osalta alkuperäisestä aineistosta. Lukitulta tilikaudelta on nimittäin hävinnyt tositteita siirtovelkojen syntymisestä, ja jäljelle jääneet siirtovelat sekä siirtosaamiset näkyvät tase-erittelyssä väärillä selitteillä.

Korjailen puuttuvat tositteet avaamalla lukitun kirjanpidon ja lisäämällä kadonneet tositteet takaisin käsin, koska data on luultavasti ollut solmussa jo pitkään ja sen juurisyytä voi olla vaikeaa löytää satojen muokkausten jälkeen (kokeilin tyhjästä uutta Kitupiikki-importia ja kaikki näytti OK:lta). Tuo virheellinen tase-erittely sen sijaan saattaa olla helpommin eristettävä bugi:

Kun menen Raportit -> Tase-erittely -> 1.1.2020–31.12.2020, niin Kitsas generoi PDF:n, jossa useilla tase-erillä on oikea tositteen tunniste, päivämäärä ja summa, mutta seliteteksti on peräisin väärältä tositteelta, joka saattaa olla jopa väärältä tilikaudelta. Esim.

* Siirtosaaminen tositteelta 56/20: selite on tositteelta 60/20
* Siirtosaaminen tositteelta 57/20: selite on tositteelta 60/20
* Kolme siirtovelkaa tositteelta 8/20: selitteet ovat tositteilta 22/21, 23/21 ja 24/21 (eli myös väärältä tilikaudelta, tulevaisuudesta)

Käytössä Kitsas 3.1.1. Tutkin mielelläni hieman kannan datasta ja koodista mistä voisi olla kyse, jos tökkäät oikeaan suuntaan.

**Comment by rjoonas** [comment]
Täydennän vielä, että tämä ei koskenut ainoastaan tilikauden lopussa avoimeksi jääneitä tase-eriä, vaan joudun näköjään käymään läpi ylipäätään vähän kaikki Kitupiikissä tehdyt tase-eräkohdennukset.

Kaikki mikä on ollut Kitupiikissä muotoa ”tosite A luo uuden tase-erän ja tosite B kohdentuu tähän tase-erään” on muuttunut jossain vaiheessa Kitsaassa muotoon ”tosite A kohdentuu satunnaiseen tase-erään samalta tai seuraavalta tilikaudelta ja tosite B kohdentuu tositteeseen A”.

**Comment by artoh** [comment]
Bugi #1128

**Comment by rjoonas** [comment]
Jees, mä suljen tämän. :)
