### ISSUE TITLE
käyttäjätoive: raportti yksittäisen tilin avoimista tase-eristä

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#1166]
Käyttötarkoituksena ennakkomaksujen täsmäytys tavran saapimisen mukaan.
(Tieto saatavissa tase-erittelystä, jätetään odottamaan toivotaanko ominiasuutta enemmänkin)

**Comment by PetriRa** [comment]
Tase-erittely listasi kaikki. Tilin asetuksissa oli "Täysi erittely Tase-erillä". 

Muutin asetusta, "Tase-erien luettelo", nyt antaa vain avoimet kuten halusin. 

Perun pyyntöni, pärjään tällä.
