### ISSUE TITLE
Käyttäjäkohtainen laskun lähettäjän nimi ja osoite

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1182]
Kun sähköpostiasetukset ovat kirjanpitokohtaisia ja käyttäjä on kirjautuneena pilveen, voi hän valita, että laskun lähettäjän nimi ja email ovat kuitenkin käyttäjäkohtaisia (toisin sanoen eri käyttäjät voivat laskuttaa omista osoitteistaan)

![Image](https://user-images.githubusercontent.com/1282146/180949609-21ce2811-0e49-4124-9bce-059ad361e85e.png)

**Comment by helihyv** [comment]
Käyttäjä A tekee ensin sähköpostisasetukset eikä laita ruksia kohtaan "vain minun lähettämissäni viesteissä". Kun toinen käyttäjä B sitten ruksaa "vain minun lähettämissäni viesteissä" ja vaihtaa nimen ja sähköpostiosoitteen, toimii lähetys hänen osaltaan oikein. Käyttäjällä A näkyy kuitenkin asetuksissa B:n antama nimi ja A:n antama osoite. (Laskut lähtevät asetuksissa näkyvillä tiedoilla.
