### ISSUE TITLE
Laskun PDF-tiedoston nimeksi tulee pelkkä numero (esim. 1.pdf) (3.3-alpha.3)

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#1185]
Lähtevässä sähköpostissa laskun tiedostonnimessä on vain numero ja pääte.
Havaittu vain pilvikirjanpidossa Kitsaan palvelimen kautta lähetetyissä laskuissa. 
Kirjanpitoon talllentuva tiedostonnimi on muotoa lasku1.pdf

**Comment by artoh** [comment]
Finvoice-määritykset vaativat laskulle nimeä 1.xml ja laskukuvalle 1.pdf
