### ISSUE TITLE
Tiliotteella (siirrossa) huoneistokohtainen kohdennus ei näy rivillä lisäysdialogista palattaessa

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1191]
Tallennettua tositetta avattaessa huoneistokohtainen kohdennus näkyy rivillä.

**Comment by helihyv** [comment]
3.3-alpha.6: huoneistokohtaisena ennen tallentamista (oikein mutta ilman tietoa mikä huoneisto) näkynyt kohdennus näkyy tallennettua tositetta uudelleenavattaessa  kohdennuksena yksittäiselle laskulle. Loki-välilehden mukaan olisi tallentunut oikea huoneistokohtainen kohdennus .
