### ISSUE TITLE
Tilikauden puuttumisen estäessä toistuvien laskujen luomisen ei virheilmoitusta tule eikä niitä yritetä myöhemmin luoda uudestaan

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1194]

**Comment by artoh** [comment]
Virheilmoitus jos ollaan tilikauden ulkopuolella ja tulisi uusittavia

**Comment by helihyv** [comment]
Virheilmoituksen tekstistä puuttuu sana ("voi") eikä termiä toistuvat laskut ole mainittu, mikä voi hämätä käyttäjää
