### ISSUE TITLE
ALV-ilmoitinaineisto, hakemisto

### ISSUE THREAD

**Issue by PetriRa** [artoh/kitupiikki#1200]
Valittu hakemisto tallennetaan ja sitä ehdotetaan seuraavalla kerralla

_Originally posted by @artoh in https://github.com/artoh/kitupiikki/issues/1091#issuecomment-999444938_ 

Tämä ominaisuus on mennyt rikki, käsittääkseni version 3.2.1 myötä. On ehdotellut pitkin kesää tallennuspaikaksi ohjelmakansiota.

**Comment by artoh** [comment]
Vaihdettu käyttämään kp()->settings() jolla vaikutusta, kun Windowsin portable-versio

**Comment by helihyv** [comment]
Hakemistosta tallentuu nyt (3.3.-alpha.11) vain hakemiston nimi, ei koko polkua. Siksi löytää hakemiston vain, jos se on ohjelmakansion alihakemisto.
