### ISSUE TITLE
Bannerin käyttöliittymän ruotsinnos

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1203]

**Comment by helihyv** [comment]
Laskulla vaihtoehto "Ei banneria" suomeksi ruotsinkielisessäkin käyttöliittymässä. Bannerien asetusivusta puuttuu käännökset. Dialogista puuttuu käännökset, paitsi niistä napeista joiden tekstit ovat muissakin dialogeissa. Virheilmoitus väärästä kuvasuhteesta suomeksi.  Asetussivujen listassa "Laskujen bannerit suomeksi".
