### ISSUE TITLE
Bugi: Kalenteri ei aukea "Laskun maksu"-ikkunan päivämääräkentässä

### ISSUE THREAD

**Issue by kankaristo** [artoh/kitupiikki#1210]
Kun Kitsaassa tekee seuraavan:
- "Uusi tosite"
- Tositetyyppi: "Siirto"
- "Laskun maksu" (oikealta alhaalta)

Avautuvassa ikkunassa päiväkmääräkenttään saa syötettyä päivämäärän näppäimistöllä/tekstillä, mutta oikean laidan kalenterikuvake (josta kaikkialla muualla aukeaa kalenteri päivämäärän valintaan) ei tee mitään klikatessa. Muuten päivämääräkenttä toimii normaalisti, eli päivämäärän saa syötettyä oikein.

Ja toinen pieni bugi samassa päivämääräkentässä (ja mahdollisesti kaikissa muissakin päivämääräkentissä): välilyönnin painaminen muuttaa päivämäärää melko oudolla tavalla, olisi varmaan hyvä jos ei tekisi mitään (tai ehkä toimisi oikean nuolinäppäimen tavoin).

-----

Kitsaan versio: 3.2.1
Käyttöjärjestelmä: Ubuntu 22.04

**Comment by artoh** [comment]
Kalenterin päivämäärävalinta jää tuossa muiden ikkunoiden alle.
