### ISSUE TITLE
Kirjanpitoa luotaessa tilikartan vaihdos sivulle palattaessa ei päivitä valintoja

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#1236]
Jos kirjanpitoa luotaessa valitsee elinkeinoelämän tilikartan, peruuttaa seuraavalta lehdeltä takaisin ja valitsee yhdistystilikartan, on seuraavalla sivulla yhä valittavana yrityksen yritysmuodot ja kirjanpitoon tulee yritystilikartta. Vastaavasti toisinpäin. (Kieltämäättä harvinainen tilanne todellisessa käytössä ja käyttäjän pitäisi toki huomata molemmissa väärät yritysmuotovaihtoehdot.)

**Comment by artoh** [comment]
Korjattu -> nyt tyhjentää yhteystiedot yms jos peruutetaan.
