### ISSUE TITLE
Käyttäjätoive: mahdollisuus rajata tositekooste vain kulutileihin

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1297]
Tulojen mukanaolo tuo käyttäjällä tositekoosteeseen mukaan pitkiä tiliotteita.

**Comment by helihyv** [comment]
Sekä "tulot" että "menot" -valinnoilla tulostetaan sekä menot että tulot.

**Comment by artoh** [comment]
dbd54290b6bb6f79ddc6048921cdb792b4f4d828
