### ISSUE TITLE
Tavaroiden maahantuonti EU:n ulkopuolelta

### ISSUE THREAD

**Issue by hasseb** [artoh/kitupiikki#1304]
Jos tiliotteellta löytyy korttitapahtuma, että on ostanut 100 € tuotteita AliExpressistä ja tekee tapahtumasta tositteen, niin ei ole mitään järkevää veroluokkaa ostokselle. Aiemmin valikossa oli muistaakseni mahdollisuus valita "Maahantuonti EU:n ulkopuolelta". Nyt jos valitsee vain vero 0%, niin veroilmoitukselle ei tule mitään kohtaan maahantuonti EU:n ulkopuolelta.

Valikossa on vaihtoehto "Tavaroiden maahantuonti, veron kirjaus", mutta sen käyttö on vähintäänkin hämärää ja todennäköisesti koko tapahtuma katoaa tiliotteelta, jos valitsee "Tavaroiden maahantuonti, veron kirjaus".

Alv-valikossa pitäisi siis olla vaihtoehto "Tavaroiden maahantuonti EU:n ulkopuolelta", joka merkkaisi verottoman hinnan oikealle tilille ja alvit oikein ja veroilmoituksen kohdan tavaroiden maahantuonti EU:n ulkopuolelta oikein.

**Comment by artoh** [comment]
Nykyisten säännösten mukaisesti kaikki EU:n ulkopuolelta tulevat paketit on
tullattava, ja alv-säännöstön mukaan puolestaan maahantuonnista maksettava
ALV määräytyy tullauspäätöksessä olevan tullausarvon mukaisesti, joka ei
välttämättä ole sama kuin ostohinta. Tämän takia maahantuonnin alv
kirjataan vasta kun tullauspäätös on saatu niin että tositteena käytetään
tullauspäätöstä.

ke 5. huhtik. 2023 klo 10.10 Hans Baumgartner ***@***.***)
kirjoitti:

**Comment by hasseb** [comment]
OK, kiitos nopeasta vastauksesta. Olihan tuosta myös selkeä ohje Kitsaan ohjeissa.
