### ISSUE TITLE
suoriteperusteisen laskun ilman toimituspäivää tallennus epäonnistuu virheeseen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1316]
Ainakin ryhmälaskussa, tarkistettava onko myös tavalisessa laskussa

Korjataan estämällä moisen laskun tallentaminen käyttöliittymästä

**Comment by helihyv** [comment]
Ryhmälaskussa tilanne ennallaan korjauksen jälkeen, epäonnistuu palvelinvirheeseen.
Yksittäisessä laskussa ei anna tallentaa valmiina/lähettää, koska toimituspäivälle ei ole tilikautta.
