### ISSUE TITLE
4.0.5: alennusprosenttia ei saa syötettyä näppäimistöltä takaisin nollaksi

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1318]
Riville kirjoitettaessa nolla ei tallennu (palautuu ennalleen), lisätietodialogi ei suostu poistamaan ainoaa merkitsevää numeroa eikä korvaamaan sitä nollalla

**Comment by helihyv** [comment]
Toimii, kunhan on ensin syötetty hinta. Ilman hintaa muuttaa väkisin nollaksi.
