### ISSUE TITLE
Liitteiden lisääminen ilman käsittelyä

### ISSUE THREAD

**Issue by Cryszon** [artoh/kitupiikki#1339]
Olisiko mahdollista saada lisättyä liitteitä (kuvia) sellaisenaan ilman käsittelyä? Olen säätänyt skannausasetukset niin, että dokumenteista tulee sopivan kokoisia oikeilla säädöillä jo skannausvaiheessa. Kitsaaseen lisättäessä tiedostojen koko paisuu melkein nelinkertaiseksi ja kuvanlaatu heikkenee.

**Comment by artoh** [comment]
Mihin tiedostomuotoon tallennat?

Yksi ajatus tuossa kuvien muunnossa on varmistaa arkiston säilyvyys, minkä takia kaikki kuvat on muutettu jpg-muotoon (aukeaa melkoisen varmasti vaaditun arkistointiajan).

Mahdollinen toimintatapa olisi säätää tiedostolle kokorajoitus (megatavuissa), mitä pienempiä kuvia ei skaalattaisi.

**Comment by Cryszon** [comment]
1-bittinen harmaasävyinen (eli toisin sanoen mustavalkoinen) `.png`. Oman kokemukseni mukaan `.png` säilyttää mustavalkoisissa kuvissa laadun paremmin pienemmällä tiedostokoolla. Tuo yhteensopivuusnäkökulma on erittäin hyvä huomio, mutta en usko, että kumpikaan (`.png` tai `.jpg`) on katoamassa mihinkään lähiaikoina.
