### ISSUE TITLE
Tyhjän kumppanin luomisen estäminen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#1366]
Uutta kumppania lisättäessä nimi ei saa olla tyhjä

**Comment by helihyv** [comment]
5,2.-RC (pre) Tyhjä estetty, pellkiä välilyöntejä sisältä yhä sallittu

**Comment by helihyv** [comment]
5.3 (pre) Pelkkiä välilyöntejä sisältävän voi yhä luoda. Sellaiseen tehtyjä muutoksia ei saa tallennettua, ei vaikka muokkaisi sille kelvollisen nimen.
