### ISSUE TITLE
Tyhjän tositteen avaaminen uudestaan

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#138]
Tallensin vahingossa tositteen, jossa ei ollut yhtään vientiä. Tätä tositetta ei saa avattua mistään, jotta sitä pääsisi muokkaamaan.
Ehdotan, että Selaa-näkymän tositteissa näkyisivät kaikki tositteet riippumatta siitä, onko niillä vientejä kirjattuna.

Vai onko jokin toinen tapa päästä tarkastelemaan ja muokkaamaan kyseisenlaisia tositteita?

**Comment by artoh** [comment]
Kaikkien tositteiden pitäisi näkyä selauksessa, mutta sql-kysely on sellainen että ei näy.
On ihan luvallista tallentaa tosite ilman yhtään vientiä (esim. liitetietotositteet sähköisessä kirjanpidossa)

**Comment by artoh** [comment]
Korjattu aa6acb713c5b6e6e9b7dc2428da06afe0a0ae0a5
