### ISSUE TITLE
Invoice per invoice value breakdown in pdf export

### ISSUE THREAD

**Issue by 145818** [artoh/kitupiikki#1383]
When exporting the Tilinpäätös after having locked it and clicking Tulosta tilinpäätös, how can I get the Liikevaihto (3000 Myynti) breakdown, i.e. not only the full sum of all the invoices associated but see in the report the invoices it added to get the value its reporting?

(Kitas 5.4.3, Linux)

**Comment by helihyv** [comment]
List of individual bills is not part of the "Tilinpäätös" (financial statement). Event level breakdown of all accounts is available in the separate "Pääkirja" report, where you can also select just an individual account.  For invoices there is also the separate "Laskut" report where you can choose between sales and purchase invoices and between open/all invoices.
