### ISSUE TITLE
5.5.2 Mac: ALV prosentti lasku virheitä kirjatessa

### ISSUE THREAD

**Issue by samip5** [artoh/kitupiikki#1392]
Näyttää siltä, että prosentti laskut ei ihan onnistu jostain syystä. Onko tietoa mistä voisi johtua? Vai onko kyse siitä, että noissa parissa laskuissa on ihan virhe? :o

![Screenshot 2024-05-29 at 8 23 52](https://github.com/artoh/kitupiikki/assets/1703002/b3b760fc-9a42-4891-8632-1e0f43c15c68)
![Screenshot 2024-05-29 at 8 18 35](https://github.com/artoh/kitupiikki/assets/1703002/ddc05faa-89c9-4422-9058-a028b5e8154b)

**Comment by helihyv** [comment]
147.42/1,24=118,887 (pyöristyy 118,89) ja 152.55/1,24=123,02 eli nuo Kitsaan nettosummat on laskettu oikein bruttosummasta. Ensimmäisessä laskussa ero tulee alv:n pyöristyksestä tasenteiksi,. Verottajan laskuohjeiden mukaisesti käytettäisiin normaalilla aritmeettista pyöristystä, laskussa näyttäisi olevan pyöristetty aina ylöspäin -periaatteella. Toisessa laskussa onkin jo vähän isompi virhe.

**Comment by samip5** [comment]
> Toisessa laskussa onkin jo vähän isompi virhe.

Siellä oli laskurivillä piilossa ALV0 rivi, 3.65€... :D Huonoin mahdollinen tapa esittää toi erittely.
