### ISSUE TITLE
Rivien järjestys tositteella

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#157]
Jos tiliotteen tuo Tuonti-toiminnolla, ja tiliotetta kirjatessa lisää vientirivejä automaattisesti tuotujen vientien väliin, niin nämä uudet vientirivit järjestyvät tositteen loppuun kun tositteen avaa uudestaan tarkastelua varten. Loogisempaa olisi, että rivit asettuvat niille paikoilleen, minne ne on lisätty tositetta muokattaessa.

**Comment by artoh** [comment]
aeba2d5ecd5aebda1ff28a7627a48632c7e7b316 Korjattu tietokantamuutoksen yhteydessä
