### ISSUE TITLE
Tase-erittely arkistossa / täysi erittely tase-erillä - laskentavirhe

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#164]
Tase-erittely laskee omiaan, ks. kuvat alla.

Olen määritellyt vastattavaa-tilin, joka tase-erittelyllä näyttää täyden erittelyn tase-erillä. Kaikki tase-erät on tuotu tilinavauksen yhteydessä, tilinavaus-tositetta (31.12.2017) on muokattu laittamalla jokainen tase-erä erikseen kredit-kirjauksilla. Tilikauden aikana saldoa on vähennetty debit-kirjauksilla, jotka on tositteilla kohdennettu näille tilinavauksen yhteydessä luoduille tase-erille.

1. Ne tase-erät, joiden summa on pysynyt samana (ei tapahtumia), näyttävät ensin oikean alkusumman (kuvassa 19,76), sitten tuplamäärän vähennyksiä edellistilikaudella, ja lopuksi oikean saldon vastaluvun.
    ![image](https://user-images.githubusercontent.com/1469093/39038531-6ec02a46-448c-11e8-8553-1f9140f1b358.png)

2. Ne tase-erät, joiden saldo on vähentynyt, mutta ei poistunut kokonaan, näyttävät ensin oikean alkusaldon (kuvassa 29,81), sitten samanlaisen tuplavähennuksen kuten edellisessäkin. Tase-erän saldo on vähentynyt yhdellä 10 euron kirjauksella (neljäs rivi), oikea loppusumma (19,81) on kolmannella rivillä mutta päivämäärä on väärä ja loppusaldo on alkusaldon vastaluku.

    ![image](https://user-images.githubusercontent.com/1469093/39039200-bfe084f6-448d-11e8-8f4c-5fd7b1110630.png)

3. Ne tase-erät, joiden saldo on vähentynyt kokonaan, näkyvät niin kuin olettaisikin: oikea summa alussa (150,07) ja tässä tapauksessa yksi vähennys samalle summalle.

    ![image](https://user-images.githubusercontent.com/1469093/39038784-f7ddb49c-448c-11e8-82ab-8e9a3b8b75e0.png)

0.10.1-beta, Windows 10

**Comment by artoh** [comment]
Liittyy mahdollisesti avaavan tase-erän merkintätavan muutokseen tietokannassa. Pitää tarkastaa myös muuta tase-erän tyypit.

**Comment by artoh** [comment]
Toisen rivin (vähennykset edellisen tilikauden loppuun saakka) kysely haki vähennyksiä tämän tilikauden loppuun saakka, jonka takia riville tuli myös kuluvan tilikauden vähennykset.

**Comment by mkouhia** [comment]
Moi!
0.11.1-beta käytössä.

Joko en ihan ymmärrä miten näiden erittelyiden pitäisi toimia, tai sitten niissä on edelleen vikaa. Esim. avauskirjausten käsittely lisäykset/vähennykset -rivillä?

Ensimmäisen kommentin esimerkkeihin viitaten:
1. Ensimmäinen esimerkki on pysynyt samana kuin aiemmassa
    ![image](https://user-images.githubusercontent.com/1469093/39231081-902c9992-4871-11e8-96e9-3c3e0d400fd9.png)
    Jos kuitenkin tälle tase-etälle on tehty vain yksi avaava kirjaus, niin mistä nuo lisäykset ja vähennykset tulevat? Eikö tämän pitäisi näyttää seuraavalta?
    ![image](https://user-images.githubusercontent.com/1469093/39230921-0407dfb2-4871-11e8-8066-27592e278594.png)
2. Toinen esimerkki, muuttunut mutta sama homma lisäysten/vähennysten kanssa
   ![image](https://user-images.githubusercontent.com/1469093/39231148-c6ec1e80-4871-11e8-93af-f661ee0700a6.png)
    Pitäisi olla seuraavasti
    ![image](https://user-images.githubusercontent.com/1469093/39231461-c9761cae-4872-11e8-9c0c-c576e8a86e47.png)
3. Ja kolmas esimerkki, uusi tase-erittely
    ![image](https://user-images.githubusercontent.com/1469093/39231303-46bd442c-4872-11e8-8a50-a79843dc649f.png)
   ja odotettu lopputulos:
    ![image](https://user-images.githubusercontent.com/1469093/39231375-789c27e2-4872-11e8-97a2-b04096524030.png)

**Comment by artoh** [comment]
Pitää selvittää, liittyykö tämä tase-erien tulostukseen vai onko tilinavauksen tase-erittämisessä tai tietokannan päivittämisessä jotain hämärää. Tietokannassa ennen 0.11 tase-erän avaavan viennin eräid oli NULL, nyt tase-erän avaavan viennin eräid on sama kuin viennin id (näin koko erällä on sama eräid ja saldon laskeminen on yksinkertaisempaa millä on merkitystä, kun laskuille ei enää ole omaa taulua vaan laskujen avoin saldo lasketaan myös eräid:n avulla)

Toistuuko ongelma, jos kirjanpito on luotu 0.11-versiolla?

Omalla kokeilulla [0.11.1 @ linux] tase-erät tulevat oikein

![uploads/46f07413-b40f-47a1-b184-32aff7684965/eria.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F46f07413-b40f-47a1-b184-32aff7684965%2Feria.png)

Joskin tässäkin tositetunnukseen voisi liittää vuosiluvun niin kuin muuallakin.
Lisäksi pitää miettiä, pitäisikö alemmassa olla selvyyden vuoksi kuitenkin nollarivi lisäykset ja vähennykset ja jäljellä-rivi.

**Comment by artoh** [comment]
Ennen versiota 0.8 (commit 5dd918496561f29dd51a5814bfc428b83365585f ) merkittiin poistetut tositteet laittamalla tositteen päivämääräksi NULL. Poistettavat kirjaukset jäivät siis vientitauluun ja aiheuttavat siellä virheitä tase-erien laskennassa. (Taisi olla syy siihen, että nyt poistettavat tositteet, viennit ja liitteet todella poistetaan tietokannasta)

Olisiko mahdollista, että kirjanpidosta löytyisi tällaisia tietueita?

`select * from vientivw where pvm is NULL`

Omissa testeissa tase-erittely näyttää toimivan, mutta laittakaa ihmeessä ilmoituksia mitä virheitä vielä löytyy!

![uploads/bf56e4dc-9fcb-46c6-be87-5eea1c27121f/Screenshot_20180501_191136.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbf56e4dc-9fcb-46c6-be87-5eea1c27121f%2FScreenshot_20180501_191136.png)

**Comment by mkouhia** [comment]
NULL-päivämääräisiä tietueita ei löydy:

    sqlite> select * from vienti where pvm is NULL;
    sqlite>

Tässä miltä kyseiset viennit näyttävät tietokannassa:

```
sqlite> select * from vientivw where eraid is 314;
vientiId    pvm         debetsnt    kreditsnt   selite          kohdennusId  eraid       kohdennus   tositelaji  tunniste    tositeId    tositelajiId  tilinro     tilinimi         tilityyppi
----------  ----------  ----------  ----------  --------------  -----------  ----------  ----------  ----------  ----------  ----------  ------------  ----------  ---------------  ----------
314         2017-12-31              1976        xxxxxxxxxxxxxx  0            314         Yleinen     *                       0           0             2021        xxxxxxxxxxxxxxx  B

sqlite> select * from vientivw where eraid is 313;
vientiId    pvm         debetsnt    kreditsnt   selite          kohdennusId  eraid       kohdennus   tositelaji  tunniste    tositeId    tositelajiId  tilinro     tilinimi         tilityyppi
----------  ----------  ----------  ----------  --------------  -----------  ----------  ----------  ----------  ----------  ----------  ------------  ----------  ---------------  ----------
313         2017-12-31              2981        xxxxxxxxxxxxxx  0            313         Yleinen     *                       0           0             2021        xxxxxxxxxxxxxxx  B
1132        2018-04-16  1000                    xxxxxxxxxxxxxx  0            313         Yleinen     MT          13          68          5             2021        xxxxxxxxxxxxxxx  B

sqlite> select * from vientivw where eraid is 315;
vientiId    pvm         debetsnt    kreditsnt   selite          kohdennusId  eraid       kohdennus   tositelaji  tunniste    tositeId    tositelajiId  tilinro     tilinimi         tilityyppi
----------  ----------  ----------  ----------  --------------  -----------  ----------  ----------  ----------  ----------  ----------  ------------  ----------  ---------------  ----------
315         2017-12-31              15007       xxxxxxxxxxxxxx  0            315         Yleinen     *                       0           0             2021        xxxxxxxxxxxxxxx  B
1142        2018-04-16  15007                   xxxxxxxxxxxxxx  0            315         Yleinen     MT          13          68          5             2021        xxxxxxxxxxxxxxx  B
```

Testaan myöhemmin miltä näyttää jos luon kokonaan uuden kirjanpidon 0.11-versiolla

**Comment by artoh** [comment]
Mahtaisiko vienti-taulusta löytyä näillä eraid:illa mitään mielenkiintoista? Jos viite-eheys on rikki niin jäävät pois vientivw:ltä. Jostainhan nuo lukemat ovat peräisin...

**Comment by mkouhia** [comment]
Ohessa ko. testin tietokanta ja arkisto, jos auttaisi debuggausta.
[TESTI-kokeilu.zip](https://github.com/artoh/kitupiikki/files/1967223/TESTI-kokeilu.zip)

**Comment by mkouhia** [comment]
Jes, mainiota! :+1:
