### ISSUE TITLE
Usean liitetiedoston lisääminen vetämällä

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#172]
Tietostojärjestelmästä on valittu useampi pdf-tiedosto ja ne vedetään tositteen "raahaa tähän" -laatikkoon. Tulos: yksikään tiedosto ei liity tositteelle. Tositteiden nimet tulevat liitteet-laatikkoon, mutta niitä ei voi avata.

**Comment by artoh** [comment]
Versioon 0.11 liitteiden käsittelyä on uudistettu ja tämä tuntuu toimivan ;) Tulee testattavaksi lähiaikoina.

**Comment by artoh** [comment]
Windowsilla raahausongelma liittyen siihen, että tiedostopolkun alkuun tulee / : /D:/data ...
