### ISSUE TITLE
Tositteen kommenttien muotoilu arkistossa

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#173]
Tositteen kommentti-kentässä voi lisätä rivinvaihtoja ja nämä säilyvät tässä kentässä. Arkistossa rivinvaihdot on siivottu ja teksti tulee yhteen putkeen. Ehdotan, että muitoilu kuitenkin pysyisi samana kuin kirjoitettu.

**Comment by artoh** [comment]
Muutetaan rivinvaihdot <br>-tageiksi
