### ISSUE TITLE
Näppäinoikoteiden näkyminen ohjelman käyttöliittymässä

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#180]
Kitupiikin ohjesivulla on dokumentoitu näppäinoikoteitä (esim. sivuilla [selaaminen] ja [kirjaaminen]). Nämä eivät kuitenkaan näy käyttäjälle ohjelmaa käyttäessä. Näppäinoikoteiden muistamista ja opettelua helpottaisi, kun niitä ei tarvitse etsiä käyttöohjeesta. Ehdotan, että näppäinoikotiet näkyisivät käyttöliittymässä esimerkiksi tooltipeinä, kun kursorin vie jonkin painikkeen päälle.

[selaaminen]: https://artoh.github.io/kitupiikki/selaus/ "Selaaminen ja etsiminen"
[kirjaaminen]: https://artoh.github.io/kitupiikki/kirjaus/ "Kirjaaminen"

**Comment by artoh** [comment]
Toteutettu tooltip osaan dialogeja
