### ISSUE TITLE
0.11 kaatuu käynnistyksessä

### ISSUE THREAD

**Issue by priikone** [artoh/kitupiikki#182]
Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00000000004c7743 in LiiteModel::asetaPdf(QByteArray const&, QString const&) ()
(gdb) bt
#0  0x00000000004c7743 in LiiteModel::asetaPdf(QByteArray const&, QString const&) ()
#1  0x00000000004653e2 in Kirjanpito::asetaLogo(QImage const&) ()
#2  0x0000000000466e2b in Kirjanpito::avaaTietokanta(QString const&) ()
#3  0x000000000045805f in KitupiikkiIkkuna::KitupiikkiIkkuna(QWidget*) ()
#4  0x000000000043e876 in main ()

**Comment by artoh** [comment]
Hups!

Tietyissä tapauksissa kirjanpitoa päivitettäessä oikein kaunis NULL POINTER

Kiitos nopeasta ja selkeästä ilmoituksesta, jolla virhe oli nopea paikantaa!
