### ISSUE TITLE
Nollasaldoinen tasetili rikkoo tase-erittelyn

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#196]
Jos taseessa on tili, jonka saldo menee nollaan, sen jälkeiset tilit eivät tulostu tase-erittelyllä ollenkaan.

Erittelyltä (kuva alla) puuttuu tili 2990. Tase-erittelyllä pitäisi näkyä 0e muissa veloissa 2989 (tai ei riviä) ja 100e siirtoveloissa 2990. 
![image](https://user-images.githubusercontent.com/1469093/39699581-80322666-5202-11e8-881d-c3ae1c5c20bd.png)

Jos testin tilillä 2989 loppusaldo ei olisi 0, näkyisi myös tili 2990 tase-erittelyllä.
![image](https://user-images.githubusercontent.com/1469093/39699776-42e2fa0a-5203-11e8-96d0-951e76a469eb.png)

Testitiedosto ohessa. 
0.12-beta, Windows 10
[tase-erittely0.zip](https://github.com/artoh/kitupiikki/files/1979653/tase-erittely0.zip)

**Comment by artoh** [comment]
Yksi väärä ehtolause whilen sisällä...

![uploads/471c0c16-8186-4833-be7e-4d1e8acc7bf2/Screenshot_20180508_083445.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F471c0c16-8186-4833-be7e-4d1e8acc7bf2%2FScreenshot_20180508_083445.png)
