### ISSUE TITLE
Laskun logo

### ISSUE THREAD

**Issue by piiseli** [artoh/kitupiikki#200]
Olisko mahdollista saada laskulle logo muutenkin, kun neliönä? Eli tulostuis ihan sellasena, kuin on.

Lisäksi asiakkaan Y-tunnukselle olis hyvä olla paikka.

Kiitos!

**Comment by artoh** [comment]
Y-tunnuksen voi tässä vaiheessa syöttää Lisätiedot -kohtaan. Kitupiikkiin on tarkoitus lähitulevaisuudessa (1.1 ?) lisätä yksinkertainen asiakasrekisteri, johon myös Y-tunnus (tai ALV-tunnus kansainvälisessä käytössä) olisi hyvä tallentaa, joten Y-tunnari toteutetaan tuon muutoksen yhteydessä. 

ALV-tunnuksen kenttä antaisi mahdollisuuden myös arvonlisäverotuksen yhteenvetoilmoituksen tekemisen yhteisökaupasta.

Logon mittasuhteiden muutos vaatii muutosta kaikkiin kuuteen paikkaan, joissa logoa käytetään (ei toteuteta vielä versioon 1.0)
