### ISSUE TITLE
Versiossa 1.0-beta laskun saajan tiedot tulostuvat firman logon päälle

### ISSUE THREAD

**Issue by shapemaker** [artoh/kitupiikki#212]
Laskun muodostaminen (pdf-tiedosto siis) on näemmä mennyt rikki sen verran, että laskun saajan tiedot tulostuvat firman logon kohdalle. Edellisessä julkaisussa laskun muodostaminen toimi.

edit: Linux-versio kyseessä (Ubuntu 16.04), järjestelmäkirjastot ajan tasalla.

![screenshot from 2018-06-12 20-49-14](https://user-images.githubusercontent.com/1733822/41307665-7ca08514-6e82-11e8-88aa-a15e9607e880.png)

**Comment by artoh** [comment]
Onko Määritykset > Laskutus -sivulla ikkunakuoren mitat määritelty niin, että etäisyys yläreunaan on alle 30 mm ja ikkunan korkeus alle 55 mm?

![uploads/d38a9894-a5c9-4271-99f5-5839cfe6810f/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd38a9894-a5c9-4271-99f5-5839cfe6810f%2Fimage.png)

Jos SEKÄ etäisyys vasemmalle ETTÄ yläreunaan on nolla, käytetään ikkunakuorettomia oletusarvoja. Ikkunakuoren valinnoissa olisi ohjelman ehkä paikallaan tarkistaa, etteivät valinnat ole sellaisia että teksti tulostuu lähettäjän tietojen päälle.

**Comment by shapemaker** [comment]
Jep, tuo se oli. Pahoittelut, oma moka. Kiitoksia ja kumarrus :)
