### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [artoh/kitupiikki#214]
`libstdc++.so.6: version 'GLIBCXX_3.4.20' not found`

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Reference:
https://github.com/AppImage/appimage.github.io/pull/496

**Comment by artoh** [comment]
Qt supports Ubuntu 16.04+, so Kitupiikki will not be available in Ubuntu 14.04

**Comment by probonopd** [comment]
What do you mean by this? Qt also supports Ubuntu 14.04 (e.g., https://launchpad.net/~beineri has most Qt versions for it)

**Comment by artoh** [comment]
Ok,  16.04 is officially out-of-box supported by 5.10 https://doc.qt.io/qt-5.11/supported-platforms-and-configurations.html  (and year 2019 and end-of-life 14.04 is coming soon...)

AppImage is a great format to share Linux binaries and linuxdeployqt make it easy to deploy using a simple script. I may check later if I will build with more complex enviroment to fit AppImageHub requirements. Kitupiikki is "encrypted in Finnish" software for small audience and nobody has asked support for older distributions...

**Comment by artoh** [comment]
Version 1.0-rc compiled with Ubuntu 14.04 virtual machine
