### ISSUE TITLE
Sähköinen alv-ilmoitus

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#256]
Eli alv-kuukausi-ilmoitus sähköisenä. Tämä kun vielä muodostuisi samalla kun tekee alv-tilityksen, niin poistuisi kirotusvirheet kun ei tarvitsisi itse noita omaveroon naputella.

Tuohan on käytännössä yksinkertainen txt-file, joka sitten lähetetään verottajalle ilmoitin.fi -palvelulla. Lähes kaikki tiedothan näkyy jo suoraan arvonlisäverolaskelmalla, tietoluettelon tunnukset ja muutama lisätieto puuttuu.

https://www.vero.fi/tietoa-verohallinnosta/tietoa_verotuksest/kehittaja/ 

Tietuekuvaus, esimerkkitiedostot lopussa:
https://www.vero.fi/contentassets/ef5905e0f5b74bcba89aa9ba9c34015d/tietuekuvaus_vsralvkv.pdf

**Comment by sorsasampo** [comment]
[Raportointikoodiston tietuekuvaus](https://www.raportointikoodisto.fi/tiedoston-tekijalle/tietuekuvaus/) on tainnut olla Verohallinnolla inspiraationa.
