### ISSUE TITLE
CSV tuonti OP:sta ei toimi

### ISSUE THREAD

**Issue by joekaapa** [artoh/kitupiikki#268]
Osuuspankin tilitapahtumat eivät uppoa kitupiikkiin.

Esimerkki:
[op-esimerkki.zip](https://github.com/artoh/kitupiikki/files/2569362/op-esimerkki.zip)

Yksi rivi kerrallaan kelpaa. Nopealla testauksella ei tunnu olevan suoraan CR LF ongelma.

**Comment by artoh** [comment]
Ongelmana on ensimmäisen (otsikko)rivin lopussa oleva ; jonka takia Kitupiikki tulkitsee, että riveillä on eri määrä sarakkeita, eikä tiedosto ole kunnollinen csv
