### ISSUE TITLE
Tositteiden selausnäkymään liitesarake

### ISSUE THREAD

**Issue by JASUMAHIRO** [artoh/kitupiikki#273]
Selausnäkymässä olisi kätevää, jos liitesarake indikoisi käyttäjälle, että onko kyseiseen tositteeseen tosiasiallisesti lisätty liite taikka liitteitä.

**Comment by artoh** [comment]
Oman sarakkeen sijaan varmaan riittäisi klemmarinkuvake tositenumeron vieressä.
Pitää testata, mikä on vaikutus suorituskykyyn kun otetaan sql-kyselyyn mukaan liitesarake
