### ISSUE TITLE
ALV-saamisten kirjaus suoraan Arvonlisäverosaamiset-tilille nettokirjausmenettelyllä

### ISSUE THREAD

**Issue by sorsasampo** [artoh/kitupiikki#275]
Eikö ALV-saamiset olisi selkeintä kirjata suoraan Arvonlisäverosaamiset-tilille, eikä vasta "Tee alv-tilitys"-toimenpiteen aikana?

Nykyisellään kirjaukset tehdään **bruttokirjausmenettelyllä**:

* Osto: per ostotili an pankkitili
* Tee alv-tilitys:
  * per arvonlisäverosaamiset an ostotili
  * per arvonlisäverovelka an arvonlisäverosaamiset

Koen itse hieman hämmentäväksi sen, että ostotilille on kirjattuna sekä ostoja joista on tehty alv-vähennykset, että ostoja joista ne on vielä tekemättä.

**Nettokirjausmenettelyllä** kirjanpito menisi:

* Osto:
  * per ostotili, arvonlisäverosaamiset an pankkitili
* Tee alv-tilitys:
  * per arvonlisäverovelka an arvonlisäverosaamiset

**Comment by artoh** [comment]
Myös nettokirjaus on toki käytettävissä, lue ajatuksen kanssa nettisivujen alv-ohjeet ja käytä Kirjausapuria.

Kitupiikin alv-käsittelystä olisi kiva saada ajatuksia, koska se hämmentää aika tavalla vaikkapa Tilittimestä siirtyneitä käyttäjiä. Alv-ohjesivu onkin tarkoitus uudistaa samalla kun versioon 1.2 tulee myös kirjaaminen marginaaliveromenettelyllä.

**Comment by sorsasampo** [comment]
No niinpä onkin, nyt nolottaa!

Nostan hattua kyllä projektista, erittäin mielenkiintoinen on. Jos tulee mieleen käytettävyysparannuksia, niin ilmoittelen.
