### ISSUE TITLE
Tositenäkymään vientien esikatselu

### ISSUE THREAD

**Issue by JASUMAHIRO** [artoh/kitupiikki#281]
Tietyissä tapaukissa olisi kätevää voida tarkastella tositteen vientejä ilman, että avaa tositteen.
Tämä jouhevoittaisi merkittävästi tarkastamista ja etenkin vertailua samankaltaisten suoritteiden kohdalla, kun ei tarvitse avata ja sulkea koko tositetta.
Nykyinen näkymä sallisi sen myös käytettävissä olevan tilan puolesta.

**Comment by artoh** [comment]
Nyt en saanut ihan kiinni siitä, millaista muutosta ehdotat (voitko piirtää esimerkiksi luonnoksen kuvaruutukaappauksen päälle)

**Comment by JASUMAHIRO** [comment]
Taisin hieman hätäillä. Viennit välilehti soveltunee nykyisessä muodossaan tähän tarpeeseen.
