### ISSUE TITLE
Merkkaus aiheuttaa tietokantavirheen

### ISSUE THREAD

**Issue by mkouhia** [artoh/kitupiikki#303]
Merkkauksen tekeminen ja sen jälkeen tositteen tallentamisen yrittäminen aiheuttaa tietokantavirheen, ks. kuva alla.

![image](https://user-images.githubusercontent.com/1469093/50595497-3e5c2980-0ea9-11e9-8f02-bb410b9d1163.png)

Asialla voi olla jotain tekemistä vanhan tietokannan kanssa (kirjanpito on luotu jollain vanhoista betaversioista ja käytetty nyt jo aika pitkään) - kun luon uuden testikirjanpidon, en pysty toisintamaan ongelmaa. Käytössä Kitupiikin Windows-versiot 1.1 ja 1.3-rc.

Mistähän kannattaisi lähteä ongelmaa metsästämään?

**Comment by artoh** [comment]
Tuleeko virhe sekä uutta merkkauksellista tositetta luotaessa että merkkausta vanhempaan lisättäessä?
Jos käynnistää komentotulkista tuleeko sinne ilmoituksia?
Jos kyse muokkauksesta: 1.3 pystyy katsomaan tallennetun tositteen selvittelytiedot ...-napista, onko siellä vinkkejä

**Comment by mkouhia** [comment]
Virhe tulee sekä uutta tositetta luotaessa että merkkausta vanhempaan tositteeseen lisättäessä - niin kirjausapurilla kuin käsin luodessakin.
Komentotulkista käynnistettäessä ilmoituksia ei tule. Selittelytiedot eivät juurikaan tunnu antavan lisätietoa - alla vastikään tehdyn tositteen selvittelytiedot jolle merkkauksen tekeminen ei onnistu:


```
id,220
pvm,2019-01-02
otsikko,testilol
kommentti,
tunniste,1
tiliote,
laji,"1 [ Muu tosite]"
json,
luotu,2019-01-02T17:35:01.798
muokattu,2019-01-02T17:35:21.400
id,2555
tosite,220
vientirivi,1
pvm,2019-01-02
tili,"232 [3000 Lipunmyyntitulot CL]"
debetsnt,
kreditsnt,9900
selite,testilol
alvkoodi,0
alvprosentti,0
kohdennus,0
eraid,
viite,
iban,
laskupvm,
erapvm,
arkistotunnus,
asiakas,
json,
luotu,2019-01-02T17:35:01.798
muokattu,2019-01-02T17:35:21.400
id,2556
tosite,220
vientirivi,2
pvm,2019-01-02
tili,"103 [1900 Käteisvarat ARK]"
debetsnt,9900
kreditsnt,
selite,testilol
alvkoodi,0
alvprosentti,0
kohdennus,0
eraid,
viite,
iban,
laskupvm,
erapvm,
arkistotunnus,
asiakas,
json,
luotu,2019-01-02T17:35:01.798
muokattu,2019-01-02T17:35:21.400
"Kitupiikin versio","1.3-rc  02.01.2019 Windows 10 (10.0)"
```

**Comment by mkouhia** [comment]
Nyt taisi löytyä ongelma! Ei ole merkkaus-taulua tässä tietokannassa.

```
sqlite3 kitupiikki.sqlite
SQLite version 3.20.1 2017-08-24 16:21:36
Enter ".help" for usage hints.
sqlite> select * from merkkaus;
Error: no such table: merkkaus
sqlite> .tables
asetus      lasku       tili        tosite      tuote       vienti_old
kohdennus   liite       tilikausi   tositelaji  vienti      vientivw
sqlite>
```

**Comment by artoh** [comment]
Tämän voi korjata käsin sqlitellä seuraavasti: 

CREATE TABLE merkkaus (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    vienti          INTEGER NOT NULL
                            REFERENCES vienti(id)  ON DELETE CASCADE
                                                   ON UPDATE CASCADE,
    kohdennus       INTEGER NOT NULL
                            REFERENCES kohdennus(id) ON DELETE CASCADE
                                                     ON UPDATE CASCADE
);

CREATE INDEX merkkaus_vienti ON merkkaus(vienti);
CREATE INDEX merkkaus_kohdennus ON merkkaus(kohdennus);

Virhe ilmenee siis vain, jos tietokanta luotu ennen Kitupiikkiä 0.11 (huhtikuu 2018)

**Comment by mkouhia** [comment]
Kiitos paljon! Nyt toimii kuten kuuluukin.
