### ISSUE TITLE
Tilitapahtumia tuotaessa 'Segmentation fault: 11'

### ISSUE THREAD

**Issue by marko-asplund** [artoh/kitupiikki#366]
tuo tilitapahtumia
tyyppi: tiliote
muokkaa kirjauksen tiliä
valitse tili listasta
==> `Segmentation fault: 11`

macOS Mojave v.10.14.4
Kitupiikki v1.4

**Comment by marko-asplund** [comment]
aiemmin terminaalille tulostunut ao. ilmoitukset:

```QSqlQuery::exec: database not open
QSqlQuery::exec: database not open
libpng warning: iCCP: known incorrect sRGB profile
objc[75950]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffaa62e3c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1188aef50). One of the two will be used. Which one is undefined.```

**Comment by marko-asplund** [comment]
Testasin juuri ja Kitupiikki kaatuu vastaavasti myös Lubuntu 18.10:ssä.

**Comment by artoh** [comment]
Millainen tiedosto tuotiin?
Pystytkö laittamaan kuvaruutukaappauksen juuri ennen kaatumista?
En saanut toistettua itse Ubuntulla

**Comment by marko-asplund** [comment]
tilitapahtumia TSV-muodossa (Nordea). Yritän saada ruutukaappauksia.

**Comment by marko-asplund** [comment]
alla ruutukaappaus tuonnissa käytetyistä parametreista sekä esimerkkitiedosto millä ongelma vaikuttaisi toistuvan.

<img width="538" alt="Screenshot 2019-06-06 at 21 59 42" src="https://user-images.githubusercontent.com/1002541/59059516-d40c4280-88a7-11e9-9a92-a6aa0bc62437.png">

[tilitapahtumat-2018.zip](https://github.com/artoh/kitupiikki/files/3263096/tilitapahtumat-2018.zip)

saatko toistettua ongelman?

**Comment by artoh** [comment]
En saanut tuotua (ohjelma ei tunnistanut tiedostoa tsv-muodoksi)  tiedostoa ilman, että kävin tallentamassa OpenOfficen kautta ja sitten avautui ongelmitta. Pitää penkoa enemmän kun ennättää...

**Comment by marko-asplund** [comment]
tässä uusi yritys:
[tilitapahtumat-2018.zip](https://github.com/artoh/kitupiikki/files/3268352/tilitapahtumat-2018.zip)

saatko toistettua ongelman uudella tiedostolla?

**Comment by marko-asplund** [comment]
@artoh saatko virhetilanteen toistettua oheisella tiedostolla?

**Comment by artoh** [comment]
Jälleen online pienen tauon jälkeen ;)

Minulla Kitupiikki 1.4 Kubuntu 18.04 syö tiedoston kaatumatta, mutta lopussa on todella monta tyhjää riviä.

![image](https://user-images.githubusercontent.com/1282146/59614969-6d4e1b00-912a-11e9-99a3-4342892cb9f6.png)

Pitää selvitellä tätä.
Kakkosversioon on tulossa huomattavasti uusittu tilitapahtumien tuonti (jossa pääsee tekemään nopeammin kaksinkertaiset kirjaukset), mutta tuon julkaisuun on vielä todella pitkä matka.

**Comment by marko-asplund** [comment]
Päivitin juuri versioon 1.4.1 enkä ainakaan pikaisen testauksen jälkeen saa tätä virhettä toistettua.
Onko päivityksessä tehty muutoksia mitkä olisivat saattaneet vaikuttaa tämän virheen esiintymiseen?

**Comment by artoh** [comment]
Mielestäni tähän ominaisuuteen ei ole tuossa koskettu.

**Comment by marko-asplund** [comment]
Olen yrittänyt toistaa tätä virhetilannetta 1.4.1 versiolla. Olen myös käyttänyt uuden version tilitapahtumien syöttö-toimintoa minkä tilihakujen yhteydessä kaatumisia esiintyi toisinaan  edellisellä versiolla. En ole toistaiseksi havainnut yhtään kaatumista näissä yhteyksissä uudella versiolla. Suljen tällä perusteella raportin.
