### ISSUE TITLE
Liitteille tuki zip tiedostoille tai mahdollisuus lisätä useita liitteitä kerrallaan

### ISSUE THREAD

**Issue by olpeh** [artoh/kitupiikki#368]
Olisi kätevää jos liitteeksi voisi lisätä ZIP arkistoja tai jos voisi lisätä useita liitteitä kerrallaan.

Tällä hetkellä ZIP tiedoston sisältö näkyy binäärimuodossa esikatselussa, mikä ei ole kovinkaan haluttu ominaisuus.

**Comment by artoh** [comment]
Useamman lisääminen kerralla samalle tositteelle hyvä idea -> päätyvät kuitenkin tietokantaan erillisinä ja esikatselu saadaan käyttöön.

**Comment by artoh** [comment]
Ohjelmassa voi jo nyt lisätä useamman liitteen samalla kertaa raahaamalla ne kerralla tositteelle.

**Comment by olpeh** [comment]
Okei, hienoa.
