### ISSUE TITLE
Tietokannan versiointi ja päivitys uuden version yhteydessä

### ISSUE THREAD

**Issue by japekka** [artoh/kitupiikki#408]
Tietokannassa olisi hyvä olla olemassa versio-taulu jossa on ylläpidettynä tieto siitä että mikä on tietokannan kulloinenkin skeema versio. Taulu itsessään sisältäisi joko yhden rivin jossa on vain tieto versionumerosta ja päivitysaika jolloin tietokanta on viimeksi päivitetty.

Tällä tavoin pystytään tekemään ohjelmaan toiminto joka tarkistaa aina päivityksen yhteydessä sen mikä versio tietokannasta on käytössä. Tämän tiedon pohjalta tietokantaan voidaan ajaa muutoslauseet jotka päivittävät tietokannan samalle tasalle sovelluksen kanssa. Tästä voisi tulla käyttäjälle ilmoitus ja mahdollisuus ottaa tietokannasta varmuuskopio ennen muutosten ajoa ja jopa peruuttaa toiminnon jolloin kantaa ei päivitetä ja ohjelma suljetaaan.

Jatkossa kaikki muutokset tietokantaan tehtäisiin omiksi itsenäisiksi skripteikseen jotka suoritettaisiin aina sen mukaan jos tietokannan versio on pienempi kuin skriptin vaatima versio.

Tämä helpottaisi jatkossa sovellukseen tehtävien tietokantamuutosten tekoa eri versioiden välillä.

**Comment by artoh** [comment]
Asetuksien kenttä KpVersio
Kitupiikin päivitystoiminto löytyy db/kirjanpito.cpp :n riviltä 285 alkaen.

Kitsaalla ei toistaiseksi ole mahdollisuutta päivittää aiempaa skeemaa (tilikarttoihin on tullut niin paljon lisää tavaraa, mm. kielituki, ettei päivitys onnistu ihan pelkillä sql-skripteillä), mutta Kitsas kuitenkin tarkastaa tietokannan version:

```c++
    QSqlQuery query( tietokanta_ );
    query.exec("SELECT arvo FROM Asetus WHERE avain='KpVersio'");

...

    if( query.next()) {
        if( query.value(0).toInt() > Kirjanpito::TIETOKANTAVERSIO) {
            QMessageBox::critical(nullptr, tr("Kirjanpitoa %1 ei voi avata").arg(polku),
                                  tr("Kirjanpito on luotu uudemmalla Kitsaan versiolla, eikä käytössäsi oleva versio %1 pysty avaamaan sitä.\n\n"
                                     "Voidaksesi avata tiedoston, sinun on asennettava uudempi versio Kitupiikistä. Lataa ohjelma "
                                     "osoitteesta https://kitsas.fi")
                                  .arg( qApp->applicationVersion() ));
```
