### ISSUE TITLE
Tilinvalintaikkunan fokus katoaa (Win)

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#420]

**Comment by rjoonas** [comment]
Minulla on Macilla Kitupiikki 1.4.5:llä ongelma, joka kuulostaa samalta kuin tämä.

Kun menen muokkaamaan tositelajia, oletustilin ja oletusvastatilin syöttökentässä tilinvalintapainike ja jokainen kenttään syötetty merkki avaavat uuden tilinvalintadialogin, joka ei ota syötteitä vastaan ennen kuin tositelajin muokkausikkuna suljetaan.
