### ISSUE TITLE
Analytiikan läpinäkyvyys ja tietosuojan parantaminen

### ISSUE THREAD

**Issue by rjoonas** [artoh/kitupiikki#432]
Minulle tuli hieman yllätyksenä koodia vilkuillessani, että ohjelma ”soittaa kotiin” lähettämällä salaamattoman yhteyden yli analytiikkaa käyttäjistä. En tajunnut asentaessani antaneeni lupaa sellaiseen, vaikka ei tuo toki hirveästi henkilökohtaisesti häiritsekään.

https://github.com/artoh/kitupiikki/blob/6edd0223c1f77af19889f1b6f5872ca067d103c9/kitupiikki/aloitussivu/aloitussivu.cpp#L354-L360

Tästä tuli mieleen useampikin parannusidea:
* Käyttäjille voisi selvemmin kertoa tietojen keräyksestä, ja vähintään näytä päivitykset -asetuksen yhteydessä voisi mainita, että samalla suostuu lähettämään tietoja ohjelman käytöstä.
* Selvästi jonnekin palvelimelle (http://kitupiikki.arkku.net/tilasto/ ?) kertyy IP-osoitteita, käyttäjän yksilöivä tiiviste ja muita käyttäjätietoja. Pitäisi siis julkaista tietosuojaseloste, jotta ei-teknisillekin käyttäjille olisi läpinäkyvää, että mitä kerätään ja miksi, miten tietoja käsitellään ja suojataan, miten omat tiedot voi poistaa jne.
* Tiedot voisi siirtää salatun yhteyden yli.

**Comment by artoh** [comment]
Tilastointiselvitys on vanhentunut (!) ja vähän piilossa ohjesivulla https://kitupiikki.info/maaritykset/perusvalinnat/
Tilastoinnissa ei tallenneta IP-osoitetta (tosin lokitietoihin yhdistelemällä sekin saattaisin löytyä viimeisimpien kuukausien ajalta...)
Alkuvuoden aikana on tarkoitus siirtyä salaamattoman yhteyden ilmaispalvelimesta omalle virtuaalipalvelimelle jossa tietoturva saadaan omiin käsiin ja koska samalla tulee mahdollisuus vapaaehtoiseen rekisteröintiin, laitetaan siinä vaiheessa tietosuoja-asioitakin kuntoon.
