### ISSUE TITLE
Ryhmälaskujen tallentuminen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#452]

**Comment by helihyv** [comment]
Ryhmälaskuissa laskutettavan tiedot (ainakaan nimi) eivät näy tulostetulla laskulla. Syynä ilmeisesti se, että laskun kohtaan Nimi ja osoite ei tule nimeä (osoitetta ei testattu).

**Comment by artoh** [comment]
näin kävi jos ei ollut osoitetta ;(
