### ISSUE TITLE
mac OS: musta ruutu, kun tulosteikkuna suljetaan koko näytön tilassa

### ISSUE THREAD

**Issue by rjoonas** [artoh/kitupiikki#455]
Tulosteikkunassa on seuraava ongelma yhdistelmällä mac OS 10.15.2 (Catalina) ja Kitupiikki 1.4.5:

1. Avaa mikä tahansa tuloste vaikka painamalla Esikatsele-painiketta Tulosteet-modulissa
2. Siirrä ikkuna koko näytön tilaan ikkunan otsikkopalkin vihreällä painikkeella (käyttöjärjestelmän toiminto)
3. Paina Kitupiikin tulostevalikon Sulje-nappia. Tuloste sulkeutuu, mutta pääikkunan sijaan Kitupiikki piirtää koko ruudun mustaksi. Kitupiikkiä voi käyttää vasta, kun vaihtaa ensin johonkin toiseen ohjelmaan ja sitten takaisin.

**Comment by petriaarnio** [comment]
Näyttääpä olevan Qt:n pitkäaikainen ongelma googlauksen tuloksen perusteella, viimeisin löytämäni bugi-issue oli viime vuoden keväältä, ja taisi olla vielä auki...
