### ISSUE TITLE
mac OS: ikonit ovat suttuisia korkean pikselitiheyden näytöillä

### ISSUE THREAD

**Issue by rjoonas** [artoh/kitupiikki#456]
Kitupiikin ikonit näyttävät aika suttuisilta korkean pikselitiheyden näytöllä ainakin mac OSissa. Tässä kuvankaappaus, jossa vasemmalla on [print.png](https://github.com/artoh/kitupiikki/blob/master/kitupiikki/pic/print.png) Kitupiikin GitHub-repositoriosta Chromessa avattuna ja 50% kokoon skaalattuna sekä oikealla sama ikoni Kitupiikki 1.4.5:n ikkunassa.

<img width="276" alt="Screenshot 2020-01-16 at 22 01 36" src="https://user-images.githubusercontent.com/1095425/72558797-14a35400-38ac-11ea-8c9a-6b8894852fb2.png">

Sama skaalausongelma on sovelluksen kaikissa ikoneissa sekä esimerkiksi käyttäjän määrittelemässä organisaation logossa, kuvatiedoston alkuperäisestä resoluutiosta riippumatta.

**Comment by petriaarnio** [comment]
Sen verran ehdin asiaa jo tutkia, että vasemman reunan työkalupakin ikonit pakotetaan 32x32 kokoon tiedostossa kitupiikkiikkuna.cpp jos screenin koko on alle 1024. Kommentin mukaan läppärin näyttöä ajatellen. Ainakin iMacin 21" norminäytöllä (screenin korkeus saa arvon 977) ikonit mahtuvat erinomaisesti ja näkyvät siisteinä kun vaihdoin koon 64x64:ksi.

**Comment by petriaarnio** [comment]
Eli otsikko siinä mielessä väärin, että ikonit ovat suttuisia myös ei-retinanäytöllä.

**Comment by artoh** [comment]
kitupiikkiikkuna.cpp r. 421

```
    // Työkalupalkin namiskat sopeutuvat jonkin verran näytön kokoon, että mahtuvat läppärin näytöllekin
    QScreen *screen = QGuiApplication::primaryScreen();
    if( screen->availableGeometry().height() > 1024)
        toolbar->setIconSize(QSize(64,64));
    else
        toolbar->setIconSize(QSize(32,32));
```
Tähän pitäisi valita parempi funktio. QScreenissä olisi

> logicalDotsPerInch : const qreal
> This property holds the number of logical dots or pixels per inch
> 
> This value can be used to convert font point sizes to pixel sizes.
> 
> This is a convenience property that's simply the average of the logicalDotsPerInchX and logicalDotsPerInchY properties.

jonka avulla voisi ehkä arvioida, mitä noille nappuloille pitäisi tehdä.

Yksi vaihtoehto olisi kakkosversion näyttöasetuksissa laittaa tästä optio, jolle lasketaan oletusasetus näytöstä saatavien tietojen pohjalta.
