### ISSUE TITLE
SMTP/Emailin formaatissa vikaa(?)

### ISSUE THREAD

**Issue by olmari** [artoh/kitupiikki#520]
Havaitsin että sekä Kitupiikin että Kitsaan viestiformaatissa on jotain häikkää, esimerkiksi vastaanosttava Exim4 bouncettaa spostilla lähetetyn laskun viestillä

```
550 maximum allowed line length is 998 octets, got 77620
```

Jostain RFC:stähän tuo rajoitus tosiaan tulee, mutta ilmeisesti jokin tulkintaongelma nyt kyseessä.. Olisiko joku CR+LF tai jomman kumman puuttumisessa häntää?

**Comment by olmari** [comment]
Tutkin alkuperäistä lähtenyttä viestiä, niin en nyt sitten tiedä missä on juurisyy.. se liite-PDF on yksi pitkä base64 rivi noin tekniseltä kantilta, se on todennäköisesti syy mistä tuo herjaa, EOS onko vika Kitsaan, Exim4, vai joku muu jokeri.

**Comment by artoh** [comment]
laskut/smtp.cpp rivi 75

```
    message.append( "--frontier\n" );
    message.append( "Content-Type: application/octet-stream\nContent-Disposition: attachment; filename="+ liitenimi +";\nContent-Transfer-Encoding: base64\n\n" );
    message.append(liite.toBase64());
    message.append("\n");
```

Tuohon pitäisi vain lisätä pätkintä riveille

**Comment by olmari** [comment]
Korjaantunee versioon +1 ? :)
