### ISSUE TITLE
Ostotositteena kirjatun laskun toimittaja ei näy toimittajien listauksessa 

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#538]
Tositteen kirjaaminen tulotositteena maksutavalla lasku, ei saa sen toimittajaa näkymään (paikallisessa kirjanpidossa) toimittajien listauksessa.

**Comment by artoh** [comment]
select kumppani.id, kumppani.nimi, sum(summa.debetsnt) as summasnt, sum(avoin.sd) as avd, sum(avoin.sk) as avk, sum(vanha.sd) as vad, sum(vanha.sk) as vak from Kumppani JOIN ( select debetsnt, vienti.kumppani, vienti.id as vienti FROM Vienti JOIN Tosite ON vienti.tosite=tosite.id WHERE vienti.tyyppi=202 AND tosite.tila > 0) as summa ON summa.kumppani = kumppani.id LEFT OUTER JOIN ( select eraid,sum(debetsnt) as sd, SUM(kreditsnt) AS sk FROM Vienti GROUP BY eraid) AS avoin ON avoin.eraid = summa.vienti LEFT OUTER JOIN ( SELECT a.eraid as eraid, SUM(a.kreditsnt) AS sk, SUM(a.debetsnt) as sd FROM Vienti as a JOIN Vienti as b ON a.eraid=b.id JOIN Tosite AS tb ON b.tosite=tb.id WHERE tb.erapvm < current_date GROUP BY a.eraid) AS vanha ON vanha.eraid = summa.vienti group by kumppani.id order by kumppani.nimi
