### ISSUE TITLE
Virheitä Finvoice-verkkolaskun luonnissa

### ISSUE THREAD

**Issue by simopot** [artoh/kitupiikki#540]
Jos laskulle on määritelty asiakkaan viite, tulee Finvoicesta virheellinen:
```
 <InvoiceDate>
            <BuyerReferenceIdentifier>asiakkaan viite</BuyerReferenceIdentifier> Format="CCYYMMDD"20200315</InvoiceDate>
```
Pitäisi olla:
```
<InvoiceDate Format="CCYYMMDD">20200315</InvoiceDate>
<BuyerReferenceIdentifier>asiakkaan viite</BuyerReferenceIdentifier> 
```
Korjaantunee siirtämällä nämäkaksi asiakkaan viitteeseen liittyvää riviä ennen InvoiceDate-riviä:
https://github.com/artoh/kitupiikki/blob/master/kitupiikki/laskutus/finvoice.cpp#L248

Lisäksi `<InvoiceRow> --> <RowVatExcluded>` -elementtiin tulee laskurivin verollinen summa vaikka pitäisi olla veroton. Verollinen summa taas pitäisi olla `<InvoiceRow> --> <RowAmount>`-elementissä, joka puuttuu kokonaan.

Käytössä Kitupiikki 1.4.5 macOS:llä.

**Comment by artoh** [comment]
Kakkosversiossa (Kitsas) on kokonaan uusittu verkkolaskutustoiminto uudemman Finvoice 3.0-standardin mukaisesti, joka on sekä lähettämisen että vastaanottamisen osalta suoraan integroitavissa Maventan verkkolaskutukseen.

Ominaisuus on tällä hetkellä testauksessa ja toimii.

Näkisin, että Kitupiikin verkkolaskutusta ei enää korjata, vaan aletaan tuetaan siirtymistä uuteen versioon (tarkoitus saada tuotantoon aprillipäivänä). Kitupiikin verkkolaskutuksen ongelmien pohjimmainen syy on siinä, että niitä rakennettaessa meillä ei vielä ollut käytettävissä tarvittavia validiointityökaluja.

**Comment by simopot** [comment]
Ok, jään odottamaan Kitsasta. :)
