### ISSUE TITLE
Kahden esikatselun rinnakkainen käyttö voi jumittaa ja kaataa ohjelman

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#546]
Havaittu tasetta ja tase-erittelyä vieräkkäin aseteltaessa. Saattaa liittyä niiden ikkunoiden koon muuttamiseen.

**Comment by twotic** [comment]
Omat havainnot:
Kun esikatselun sulkee, ohjelman käyttämä muisti ei palaa esikatselua edeltävälle tasolle, joten käytetty tila kasvaa hissukseen. Vapaan tilan koosta riippuu, milloin tämä kaataa ohjelman.
Samoin, kun katseluruudun kokoa kasvattaa, myös muistinkäyttö kasvaa, joten jos ennestään ollaan lähellä rajaa, koon muutos voi olla triggerinä, vaikka ei varsinaisena syynä.

**Comment by artoh** [comment]
@twotic millä versiolla ja käyttöjärjestelmällä?

**Comment by twotic** [comment]
Kitupiikillä olen vilkaissut muutaman viikon välein aika kauan. 
Kitsas näyttää käyttäytyvän samalla tavalla, kun minkä tahansa esikatselun avaa ja sulkee toistuvasti.
Eli nyt viimeksi Win 8.1, Kitupiikki 1.4.6 ja Kitsas 2.0-beta

**Comment by twotic** [comment]
Ubuntu 19.10 samat versiot. Sama ilmiö, Kitsaassa pinnallisen tarkastelun pohjalta voimakkaampi.
while [ 0 ] ; do cat /proc/10237/statm ; sleep 3 ö done
Jos haluat muutoksen lukuina, niin ilmoita

**Comment by artoh** [comment]
Itse en ole saanut Ubuntu-kehitysympäristöä kaatumaan enää betaversiolla (aiemmilla oli ollut ongelmia myös siinä, että muistia vapautettiin liian aikaisin ja esikatseluikkunaan palaaminen kaatoi ohjelman). Mutta tutkaillaan millaista remonttia esikatselukomponetentteihin pitää tehdä.

**Comment by twotic** [comment]
Sama täällä. Minulla on niin paljon muistia että tuo hidas vuoto vaatisi hyvin monta esikatselua.
Maininta ikkunan koon muuttamisesta vain herätti ajatuksen että jos muistia on sopivan vähän se tarjoaisi mekanismin.
