### ISSUE TITLE
mac käännös v1.4.6 epäonnistuu

### ISSUE THREAD

**Issue by marko-asplund** [artoh/kitupiikki#556]
Yritän kääntää versiota 1.4.6 macissä näillä [ohjeilla](https://github.com/artoh/kitupiikki#k%C3%A4%C3%A4nt%C3%A4minen)
mutta käännös epäonnistuu.

Asennettuna ohjeiden mukaisesti Qt >  5.10 (5.14), libpopler ja libzip.

```
...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++1y  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I/usr/local/include -I/usr/local/Cellar/qt/5.14.1/lib/QtPrintSupport.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtSvg.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtSql.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtXml.framework/Headers -I/usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt/5.14.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.1/lib -o selauswg.o selaus/selauswg.cpp
[1mselaus/selauswg.cpp:270:31: [0m[0;1;31merror: [0m[1mstatic_cast from 'QEvent *' to 'QKeyEvent *',
      which are not related by inheritance, is not allowed[0m
        QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
[0;1;32m                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m/usr/local/Cellar/qt/5.14.1/lib/QtWidgets.framework/Headers/qwidget.h:75:7: [0m[0;1;30mnote: [0m
      'QKeyEvent' is incomplete[0m
class QKeyEvent;
[0;1;32m      ^
[0m[1mselaus/selauswg.cpp:271:21: [0m[0;1;31merror: [0m[1mmember access into incomplete type
      'QKeyEvent'[0m
        if( keyEvent->key() == Qt::Key_Enter || keyEvent->key() == Qt::K...
[0;1;32m                    ^
[0m[1m/usr/local/Cellar/qt/5.14.1/lib/QtWidgets.framework/Headers/qwidget.h:75:7: [0m[0;1;30mnote: [0m
      forward declaration of 'QKeyEvent'[0m
class QKeyEvent;
[0;1;32m      ^
[0m2 errors generated.
make: *** [selauswg.o] Error 1
```

Tässä tarkempi loki operaatioista:
[kitupiikki.typescript.txt](https://github.com/artoh/kitupiikki/files/4363347/kitupiikki.typescript.txt)

Miten käännös onnistuu macillä?

**Comment by marko-asplund** [comment]
Qt versiolla 5.12.7 ei vastaavaa ongelmaa ilmene.
Tosin jostain syystä sovelluksen linkitys epäonnistuu koska libzip:iä ei löydy kirjastojen hakupolusta vaikka kirjasto on kyllä asennettuna.
Kun komentoon lisää käsin `-L/usr/local/opt/libzip/lib`, linkitys onnistuu.

Ohjeeseen https://github.com/artoh/kitupiikki#vaatimukset
voisi päivittää Qt versioon liittyvät vaatimukset.

**Comment by marko-asplund** [comment]
@petriaarnio Miten saan käännettyä macillä application bundlen?
Sain käännettyä toimivan Kitupiikki-binäärin makella.
Xcode projektitiedostot sisältävät kuitenkin absoluuttisia sekä tietyn sijainnin olettavia suhteellisia polkuja  lähdekoodi- sekä Qt-kirjastohakemistoihin.

**Comment by artoh** [comment]
Kiva seurata omppupuolen aktiivisuutta! Aika pian uuden version ilmestymisen jälkeen kysellään jo, koska saadaan macille...
Kitupiikki 1.4.6:n on tarkoitus olla viimeinen Kitupiikki-puolen päivitys: kun Kitsas saadaan vakaana ulos ja siihen vielä asoy-tilikartta, aletaan enemmän ajaa siirtymistä Kitupiikistä Kitsaaseen

**Comment by petriaarnio** [comment]
Nyt olisi 1.4.6 saatavilla myös macille. Parempi myöhään kuin ei milloinkaan.

Vaikea sanoa suoralta kädeltä miksi xcode-käännös epäonnistuu, pois lukien tietysti absoluuttisia polkuja, jotka voi itse vaihtaa omalle koneelle sopivaksi tai tehdä koneelle uusi saman niminen käyttäjä. Xcode ei aikoinaan helposti taipunut käyttämään suhteellisia polkuviittauksia kirjastoihin, enkä asiaa sitten enempää tutkinut koska asia ei haitannut omaa käyttöä. Ja nyt ei enää välttämättä kannata siihen käyttää aikaa kun Kitupiikki on vaihtumassa Kitsaaseen.

Macin Kitupiikki on käännetty käyttäen Qt 5.11.0, lisäksi popplerin sekä libzipin vanhoja versioita, jotka asensin homebrew:lla. Näillä saatiin laitteistopuolella pidettyä yhteensopivuutta ainakin 2009 vuoden malleihin asti. Näitä popplerin ja libzipin versioita ei enää ole homebrewsta saatavilla, ne pitäisi kääntää itse vanhalla koneella tai ehkä sopivalla käännösparametreilla.

**Comment by marko-asplund** [comment]
Kiitos molemmille vastauksesta ja Petrille lisäksi uuden mac julkaisun teosta! 👍

Sain ladattua uuden mac julkaisun githubista, mutta [asennus-sivun](https://kitupiikki.info/asennus/#mac) linkki näyttää olevan vielä päivittämättä.

Milloin Kitsas betasta on odotettavissa mac julkaisu?

**Comment by marko-asplund** [comment]
Kokeilin juuri Kitsas v2.0-beta version kääntämistä ja törmään siinä vastaavankaltaisiin ongelmiin.
Saan käännettyä suorituskelpoisen binäärin, mutta siitä puuttuu esim. sovellusikoni.
Osaisitteko auttaa näissä?

Menettelin seuraavasti:
* `cp /usr/local/opt/libzip/lib/*.dylib /usr/local/opt/libzip`
* päivitä Qt polku ja versio tiedostoihin `copy_plugins.sh` ja `update_project.sh`
* suorita `update_project.sh`
* avaa projekti Xcodessa ja käännä

Yllä kuvatulla menettelyllä saan käännettyä suorituskelpoisen binäärin, mutta `update_project.sh` skriptin suorittamisen jälkeen esim. sovellusikoni katoaa Xcodesta.

Mitä kirjastoversioita tulisi käyttää esim. poppler, zip ja Qt-kirjastoista?

**Comment by marko-asplund** [comment]
@artoh Tein mac-latauslinkin päivityksestä PR:n https://github.com/artoh/kitupiikki/pull/559

**Comment by petriaarnio** [comment]
Kitsas @Mac beta julkaistu.

Kirjastojen versiot ovat kyllä löydettävissä Xcode-projektista.
update_project.sh käytöstä sen verran, että käytän sitä vain uuden Qt preprocessorin generointiin. Itse Xcode-projektin revertoin takaisin versiohallinnan versioon, koska siellä on paljon manuaalisesti tehtyjä muutoksia mm. kirjastojen hallinnan osalta. Uudet muutokset, lisätyt ja poistetut tiedostot, teen sitten käsin. Ei aivan sutjakka prosessi, pitänee joskus aktivoitua enemmän ja automatisoida koko juttu.

**Comment by marko-asplund** [comment]
Kiitoksia! Latasin ja testailen tuota tarkemmin.

Onko jotain helppoa tapaa muuttaa Qt-kirjaston sekä lähdekooditiedostojen ym. resurssien polut täsmäämään omaan ympäristöön? Toki varmaankin jonkinlainen `sed` -muokkaus toimisi, mutta saako polkuja muutettua jotenkin helposti esim. Xcodessa? Minulla ei ole juuri kokemusta Xcoden käytöstä sovelluskehitykseen.

**Comment by artoh** [comment]
Kiitos @petriaarnio !
Uudet versiot on nyt linkitetty lataussivuille.
Nyt pysytään aikataulussa, ajoittuu varsinaisen version julkaisu jonnekin aprillipäivän tienoille

**Comment by petriaarnio** [comment]
Lataussivulla 2.0 betan linkki osoittaa 1.4.6:n imageen.

**Comment by hasseb** [comment]
Tuo libzip kirjaston default hakemisto on tosiaan rasittava. Yleensä kääntyy Macilla suoraan, mutta aina pitää käsin käydä projetitiedostosta tuo macin libzip hakemisto käsin puukottamassa. En tiedä kenellä se on asennettuna tuohon projektitiedoston hakemistoon, mutta defaulttiasennuksella pitää aina tuo yksi alihakemisto käydä lisäämässä

**Comment by petriaarnio** [comment]
Nyt pitäisi olla vähemmän rasittava, polku korjattu.
