### ISSUE TITLE
Segmentation fault suljettaessa Valitse tili -ikkuna

### ISSUE THREAD

**Issue by anttipalsola** [artoh/kitupiikki#560]
Ajoittain Kitupiikki kaatuu suljettaessa Valitse tili -ikkuna. Tällöin komentoriville tulostuu seuraava virheilmoitus:
`Segmentation fault      (core dumped) kitupiikki`

Ongelma ei toistu joka kerta mutta on kuitenkin tapahtunut useamman kerran seuraavasti tositetta muokattaessa:

1. Lisää rivi vienteihin painamalla viimeisen rivin selitteessä Tabia.
2. Paina Shift-Tab mennäksesi muuttamaan viennin päivämäärää.
3. Valitse tili -ikkuna avautuu. (Miksi?) Valittavissa on vain tili 1114 Rakennelmat 20%. (Miksi?)
4. Paina Esc sulkeaksesi ikkuna.
5. Toisinaan Kitupiikki kaatuu tässä vaiheessa ja tallentamattomat viennit menetetään.

Käyttämäni ympäristö on Kitupiikki 1.4.5 Ubuntu 19.10:ssä.

**Comment by artoh** [comment]
Avautuva tili-ikkuna suodattaa merkillä 0, johon täsmää vain 20% -poistoinen kalustotili. Syynä mekanismi, jolla fokus siirretään tilienvalintaikkunalle.

Versiossa 2.0 näppäinten käsittely koodattu uudelleen, ja betassa näyttää toimivan.

**Comment by anttipalsola** [comment]
Lisäyksenä, että äsken kaatuminen tapahtui myös, kun ikkunan sulki hiirellä klikkaamalla.

Hyvä, jos tämä ongelma tulevissa versioissa poistuu, sen verran ärsyttävästä ominaisuudesta on kyse. En nyt vain viitsi käyttää beta-versiota oikean yhdistyksen oikeassa kirjanpidossa ja tilinpäätöksessä, joten käytän toistaiseksi 1.4.5:ttä.

**Comment by artoh** [comment]
Tällä hetkellä työn alla on kakkosversion saaminen julkaisukuntoon ja ykkössarjasta korjataan vain kaikkein kriittisimmät (=johtaa virheisiin kirjanpidossa) bugit.

Workflowna suosittelen tämän bugin kanssa, että jokaiselle riville kannattaa ensiksi syöttää tili.

**Comment by petriaarnio** [comment]
Uuden tositteen tekeminen on nyt erittäin kaatumisherkkä myös macin 2 viimeisimmässä versiossa, oli pakko palata takaisin versioon 1.4.3. joka näyttää nyt olevan viimeinen vakaa versio.

**Comment by artoh** [comment]
Suljetaan Kitupiikki-sarjan bugit
