### ISSUE TITLE
Lyhennetty maksuaika laskulla

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#564]
Laskun maksuaika päivittyisi tulostusvaiheessa vain, jos se alunperin oletusmaksuaika.
Voitaisiin toteuttaa niin, että oletusmaksuaika tallentuisi tyhjänä?

**Comment by artoh** [comment]
Lisätään laskuille valinta LaskuMaksuaikavahintaan jolloin eräpäivää päivitetään laskua lähetettäessä

**Comment by helihyv** [comment]
Laskun maksuaika päivittyy vain tulosteeseen. Laskutositteeseen jää vanha eräpäivä.
