### ISSUE TITLE
Tilinumeron säilyminen päivityksen jälkeen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#603]
Koska tilinumero lisätään tilin /init-määritteeseen, ei tiliä merkitä muokatuksi ja tilinumero ylikirjoitetaan seuraavassa tilien päivityksessä.
Ratkaisuna joko ibanin sijoittaminen omaan tietueeseensa tai pankkitilin muokkaaminen put-metodilla

**Comment by helihyv** [comment]
Testattu windows-toimivuus pilvessä.
