### ISSUE TITLE
Tosite lukittuu tilaan, jossa sitä ei voi muokata

### ISSUE THREAD

**Issue by anttipalsola** [artoh/kitupiikki#606]
Havaitsin ongelman, jossa tosite lukittuu tilaan, jossa sitä ei voi enää muokata.

Alkutilanne:

- Kitsas 2.0 RC @ Ubuntu 19.10
- Tilikausi 2019 lukittu
- Kirjauksia tehdään tilikaudelle 2020

Virhetilanteen saa syntymään seuraavalla tavalla:

1. Lisää uusi menotosite tilikaudelle 2020, tee siihen kirjauksia mutta älä lisää tositeliitettä tässä vaiheessa. Tallenna tosite.
1. Mene myöhemmin muokkaamaan tositetta ja lisää siihen PDF-muotoinen tositeliite, jossa esiintyy tilikaudelle 2019 osuvia päivämääriä.
1. Ohjelma tulkitsee tositeliitteessä olevan päivämäärän tositteen päivämäärän ja vaihtaa tositteen päivämäärän vuodelle 2019. Koska kyseinen tilikausi on lukittu, tositetta ei voi tallentaa, mikä on tietysti oikein. Kuitenkaan tositteen päivämääriäkään ei enää pysty muokkaamaan (ja siis korjaamaan takaisin vuodelle 2020).

Ongelmaa ei esiinnyt, jos liitteen lisää heti tositettaessa luotaessa. Silloinkin ohjelma kyllä lisää tositteeseen vuodelle 2019 osuvat päivämäärät mutta sallii kuitenkin niiden korjaamisen vuodelle 2020.

Mielestäni ohjelman ei muutenkaan tulisi vaihtaa päivämääriä liitetiedoston perusteella, jos käyttäjä on jo päivämäärän syöttänyt.

**Comment by artoh** [comment]
Korjataan niin, että kun tosite on jo kirjanpidossa, ei liitteen lisääminen käynnistä tuontitoimintoa.
