### ISSUE TITLE
Muu-tosite syöttö

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#622]
Muu-tositteen vientien syöttö: Debet-sarakkeesta ei pääse
Kredit-sarakkeeseen painamalla Tab, jos molemmissa on numero. Jos
Debettiin syöttää jotain, Kredit saisi kadota samalla ja toisin päin.
Kätevä olisi näppäin, jolla debetin voi vaihtaa kreditiksi.

Vientejä kirjatessa avoin summa ilmestyy automaattisesti joko Debet- tai
Kredit-sarakkeeseen. Kursori saattaa kuitenkin mennä siihen toiseen
sarakkeeseen, esim. kursori Debetiin ja summa Kreditiin. Tämä aiheuttaa
turhia painalluksia, kun väärä saldo on ensin käytävä tyhjentämässä
Debetistä, että voi kirjoittaa jotain Kredittiin tai päin vastoin.
Kursori saisi mennä samaan sarakkeeseen kuin numerokin.

Kohdennus-sarakkeesta valitun erän summa ei siirry automaattisesti
Debet/Kredit-sarakkeeseen. Summa ei edes näy, kun dropdown on suljettu.
Summa saisi näkyä ruudulla ja myös siirtyä automaattisesti viennille,
jos viennillä ei ole vielä summaa.

**Comment by helihyv** [comment]
Samalle riville voi edelleen toisinaan  lisätä lukeman sekä debit- että kredit-riveille. Toisinaan taas toimi eli edellinen lukema poistuu ja lisätään uusi rivi. .
![]()

**Comment by helihyv** [comment]
# # # # # #
![Näyttökuva (3)](https://user-images.githubusercontent.com/1296559/81644049-acb2e380-942f-11ea-8ace-6ae04e8f6b31.png)

**Comment by helihyv** [comment]
Kohdennuksesta valitun erän summa siirtyy kyllä enteriä painettaessa, mutta rivistä ei sen jälkeen näe lainkaan, että sille on kohdennus valittuna, ellei avaa kohdennusvalikkoa uudestaan.

![Näyttökuva (4)](https://user-images.githubusercontent.com/1296559/81644998-6e1e2880-9431-11ea-88fb-08adf0939d87.png)

**Comment by helihyv** [comment]
Kohdennuksen näyttäminen toimii.

Jos rivillä sekä debit että kredit sarakkeisiin syötetään summa ja painetaan enter, toisinaan luodaan uusi rivi, jolla on ensimmäisenä annettu summa toisena annetun summan kentässä. Alkuperäinen rivi muokkaantuu oikein.
Kuvakaappauksessa on ensin syötetty debet-kenttään 50, sitten syötetty kredit-kenttään 500 ja painettu enter.

**Comment by helihyv** [comment]
Sama ilmiö on yhä. En löytänyt logiikkaa, jolla niin tapahtuu.
