### ISSUE TITLE
Sähköisen arkiston tiedostoista arkisto.css ja jquery.js ei lasketa tarkistussummia

### ISSUE THREAD

**Issue by anttipalsola** [artoh/kitupiikki#627]
Kitupiikki 1.4.5:ssä (Ubuntu 19.10) luodun kirjanpidon sähköisen arkiston tiedostoista `arkisto.css` ja `jquery.js` ei lasketa sha256-tarkistussummia. Kyseiset tiedostot eivät toki sisällä mitään kirjanpitoinformaatiota, mutta periaatteessa pahantahtoinen käyttäjä voisi näitä tiedostoja muokkaamalla vääristää selaimessa lukijalle näytettävää informaatiota. Tämä taas saattaisi jäädä esim. tilintarkastajalta huomaamatta, jos hän luottaisi kirjanpidon muuttumattomuuden varmistamisessa tarkistussummiin.

Tämä on tietysti _hyvin_ kaukaa haettu skenaario ja muokkaaminen on mahdollista huomata ko. tiedostojen koodia tutkimalla (ja edellä kuvattu temppu todennäköisesti täyttäisi rikoksen tunnusmerkistön), mutta jos ei ole mitään estettä laskea tarkistussummia myös ko. tiedostoista, niin jossain tulevassa versiossa kyseisen toiminnallisuuden voisi varmaankin lisätä.

**Comment by artoh** [comment]
Jos jossain vaiheessa aikaa riittää, voisi tarkastussumman vielä aikaleimata https://www.freetsa.org/ tms. palvelulla niin hankalin vaihe eli sha-tiivisteen säilyttäminenkin voitaisiin jättää pois ja arkistohakemisto sinällään antaisi suojan muuntelulta ...

**Comment by anttipalsola** [comment]
Tarkoitatko siis, että tiiviste jätettäisiin pois tasekirjasta? Mielestäni käyttäjällä pitäisi olla ainakin optio sisällyttää tiiviste tasekirjaan, koska sen avulla kirjausketju on aukottomasti todennettavissa. 

Aikaleimaus sinänsä olisi hyvä lisä, mutta sen ei siis välttämättä tarvitsisi korvata tiivistettä.

**Comment by artoh** [comment]
Kakkosversiossa tiivistettä ei enää automaattisesti tulosteta tilinpäätökseen, vaan myös tilinpäätös sisällytetään sähköiseen arkistoon (teki miten päin tahansa, on  tässä kana ja muna -ongelma) ja arkistosta voidaan tulostaa/tallentaa sha-tiiviste erikseen talteen. Isoin syy tässä on se, että jos ohjelmalla on monta samanaikaista käyttäjää, voidaan arkisto muodostaa toisella koneella kun millä tilinpäätös on muodostettu ja silloin sha-tunniste ei enää täsmäisi.
