### ISSUE TITLE
Oletusmenotilin ja oletustulotilin käyttäminen tiliotetta tuotaessa

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#649]
Lisäksi voisi varmistaa, että nämä tilit voi valita asetuksista

**Comment by helihyv** [comment]
Tiliotteelta tuonnille on asetuksissa omat oletusmeno - ja tulotilit, mutta niiden asettaminen ei vaikuta tiliotteelta kirjattessa.
