### ISSUE TITLE
Tilin 7680 nimi "Atk-laitehankinnat (< 3v. kalusto)" ei näy oikein aloitussivulla

### ISSUE THREAD

**Issue by hasseb** [artoh/kitupiikki#650]
Voisiko tilin nimetä uudestaan "Atk-laitehankinnat (alle 3v. kalusto)". QT ei ilmeisesti oikein pidä '<' merkistä.

**Comment by artoh** [comment]
Etusivun (ja varmaan myös html-raportin, pitää selvittää) muodostamisessa ei nähtävästi ole koodattu hakasulkuja oikealla tavalla html-muotoon, korjataan...

Tilin nimissä olisi varmaan nykyiaikaisempaa puhua IT-laitteista, tilin nimessä paistaa hieman historiallista painolastia jostain ammoin muinoin muodostetusta yleiseen käyttöön vakiintuneesta tilikartasta.
