### ISSUE TITLE
Lähettämätöntä) maksumuistutusta muokattaessa, jos lisää koron  tai muistutusmaksun se ei näy  laskulla  (näytä-nappi)

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#681]

**Comment by helihyv** [comment]
Nyt korko ja muistutusmaksu näkyvät laskulla, mutta laskua ei pysty tallentamaan. (Kaikki kolme tallennusnappia ovat harmaina),
![]()

**Comment by helihyv** [comment]
![Näyttökuva (21)](https://user-images.githubusercontent.com/1296559/88808039-0dde8d80-d1bb-11ea-9957-0163c4d50013.png)

**Comment by artoh** [comment]
![]()
