### ISSUE TITLE
Raporttien käännaöversioissa voisi kääntää myös kohdennuksen "yleinen"

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#687]

**Comment by artoh** [comment]
Pääkirja ja päiväkirja

**Comment by helihyv** [comment]
Englanninkielisessä käännetty, ruotsinkielisessä ei.

**Comment by artoh** [comment]
Virhe oli tietokannan luontiskriptissä, korjattu uusilla paikallisilla kirjanpidoilla (pilveen seuraavassa tuotantoonviennissä)
