### ISSUE TITLE
Oletustileissä tiliotteelta tuotavat menot kirjatuvat oletuksena Ostot-tilille, vaikka Menot-ruksi on asetettu ja tiliksi asetettu muu tili kuon ostot

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#702]

**Comment by artoh** [comment]
![image](https://user-images.githubusercontent.com/1282146/88894798-29947300-d251-11ea-877b-ec3b410319f7.png)

Tässä näyttää toimivan

**Comment by helihyv** [comment]
Uudella toimittajalla toimii, eli ilmeisesti jäi edellisessä testissä toimittajakohtaisen oletuksen jalkoihin, kuten pitääkin.
