### ISSUE TITLE
PDF-kuitit kaatavat Mac-RC3-version High Sierra OS:ssä

### ISSUE THREAD

**Issue by peketola** [artoh/kitupiikki#716]
Kirjausten selailussa tai uuden kirjauksen luonnissa PDF-tiedostojen käsittely/katselu kaataa sovelluksen RC3-versiossa. Virheilmoituksena tulee seuraavaa:

Process:               Kitsas [10217]
Path:                  /Applications/Kitsas.app/Contents/MacOS/Kitsas
Identifier:            fi.atfos.kitsas
Version:               2.0-RC.3 (7)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Kitsas [10217]
User ID:               501

Date/Time:             2020-08-02 09:35:28.570 +0300
OS Version:            Mac OS X 10.13.6 (17G14019)
Report Version:        12
Anonymous UUID:        CFE98E26-4FF4-4964-CC2D-D6B3D62F2377

Sleep/Wake UUID:       D764BE33-8691-43C4-A8C7-721CFCEEB240

Time Awake Since Boot: 32000 seconds
Time Since Wake:       880 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Kitsas.app/Contents/MacOS/../Libraries/libpoppler.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by artoh** [comment]
@petriaarnio osaatko sanoa olisiko tässä jotain ristiriittaa kääntäneen os-version 10.15 ja ajoversion 10.13 välillä? 

Pdf-käsittelykirjasto libpoppler on jo aiemminkin osoittautunut kääntämisen kannalta haasteelliseksi.

**Comment by petriaarnio** [comment]
Tutkin huomenna asiaa tarkemmin.

**Comment by petriaarnio** [comment]
Ok syy löytyi ja julkaisin juuri rc.4:n.
Olin kääntänyt Kitsaan uudella macillä ja uusimmalla käyttiksellä. Min os version oikein 10.13 mutta homebrew:n lataa defaulttina uusimmat ko. käyttikselle käännetyt kirjastot.
Piti vaihtaa takaisin käyttämään vanhaa iMacia kun en löytänyt helppoa/järkevää tapaa pakottaa homebrew lataamaan High Sierralle käännetyt kirjastot.

**Comment by artoh** [comment]
@peketola Toimiiko nyt --> voidaanko sulkea issue?

**Comment by peketola** [comment]
@artoh @petriaarnio hienosti toimii nyt!!
