### ISSUE TITLE
Maksetun laskun valinta tiliotetuonnissa kun useammalla laskulla sama viite

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#747]
Voisi yrittää seuraavaksi euromäärällä avointen erien kesken.

**Comment by artoh** [comment]
Jos monta tase-erää, haetaan vanhin sopiva avoin tase-erä

**Comment by helihyv** [comment]
Paikallisesti  kun kolmella laskulla sama viitenumero ja eri euromäärät, kohdesi yhden laskuista molemmile riveille, joiden euromäärä ei täsmää laskun kanssa. Kolmannelle riville ei kohdentunut mitään.
