### ISSUE TITLE
Kitsas 2.0 macOS-versio

### ISSUE THREAD

**Issue by marko-asplund** [artoh/kitupiikki#748]
Voisiko virallisesta 2.0 versiosta julkaista myös macOS-paketin?

**Comment by artoh** [comment]
Löytyy jo Petrin forkista https://github.com/petriaarnio/kitupiikki/releases/tag/mac-v2.0

Ohjelman virallinen julkistus on maanantaina, jolloin win/linux/mac-versiot tulevat kotisivulta ladattaviksi.
