### ISSUE TITLE
Tiliotteen kirjaamisessa näppäimet -> enterillä eteenpäin

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#750]

**Comment by helihyv** [comment]
Windowsilla kohdennusta ei pysty kirjoittamaan riville eikä valikkoa näy, vaikka kirjanpidossa on kohdennuksia.

**Comment by helihyv** [comment]
Kohdennus toimii kuten pitääkin, eli silloin kun tili on valittuna.
