### ISSUE TITLE
Muu-tositteen rivin muokkausnäkymä

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#767]
Laajennetaan alv-valintaikkunaa niin, että rivin kaikki valinnat voidaan tehdä
- pvm
- tili
- määrä (debet/kredit)
- kohdennus
- tase-erä
- merkkaukset
- alv
  - kirjauksen tyyppi
  - alv-laji
  - alv-prosentti

**Comment by artoh** [comment]
![image](https://user-images.githubusercontent.com/1282146/95824138-73acd100-0d37-11eb-8150-fdc8cb2f65ed.png)

**Comment by helihyv** [comment]
Kodennukset valinta katosi joko  näkyvistä uusille riveille joidenkin rivien kirjaamisen jälkeen tai ei näkynyt jollekin sellaiselle tilille, jolle sen olettaisi näkyvän.

Kohdennus on näkyvissä vain osalle tileistä, mutta merkkaukset kaikille. Onko tarkoituksellista?

**Comment by helihyv** [comment]
Verokanta 24% luon 0% verokannan viennin

**Comment by helihyv** [comment]
Yhteisöostoissa arvonlisäverosaamiset kirjautuvat kredit-puolelle.
