### ISSUE TITLE
Vakioviitteiden valitseminen itse

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#772]
Järjestelmä antaisi vakioviitteele aina ensimmäisen vapaan numeron
Käyttäjä voisi siten valita vapaan vakioviitenumeron myös itse (tilanne, jossa vakioviitteitä valitaan listalta ja sitten syötetään ohjelmaan)

**Comment by helihyv** [comment]
Viitenumerola 0000 tallentuu viitenumeroton vakioviite.
Jos kirjoittaa varatun viitenumeron ja vaihtaa takaisin ensimmäiseen vapaana olevaan, OK pysyy disabloituna.

**Comment by helihyv** [comment]
Jos kirjoittaa varatun viitenumeron ja vaihtaa takaisin ensimmäiseen vapaana olevaan, muokataan kirjoitetun numeron vakioviitettä sen sijaan, että luotaisiin uusi vakioviite ensimmäisellä vapaana olevalla numerolla.
