### ISSUE TITLE
Tositteiden kokonaislukumäärä tulostuu väärin kirjanpitoaineistoon

### ISSUE THREAD

**Issue by juusoautiosalo** [artoh/kitupiikki#785]
Kitsaalla tuotettuun kirjanpitoaineistoon tulostuu tositteiden kokonaislukumäärä väärin. Kirjanpitoaineistoon tulostunut tositteiden kokonaismäärä on suurempi kuin todellinen lukumäärä.

Ongelma ilmeni yhdellä kirjanpitokerralla seuraavanlaisesti:
- Kirjanpitoaineiston viimeisellä sivulla tositteen numero on: ![kuva](https://user-images.githubusercontent.com/57953088/97923929-84190000-1d67-11eb-9d7d-460f45ee182c.png) samalla kun selaa-näkymän mukaan tositteita on 14 kpl.
- Virheellinen kokonaislukumäärä tulostuu myös esimerkiksi pääkirjaan.
- Kirjanpidon teon aikana poistin tositteita ja lisäsin osaan tositteista useamman kuin yhden tiedoston.

Käytetty ohjelma on Windows (10) asennettava ohjelma, versiotieto:
![kuva](https://user-images.githubusercontent.com/57953088/97924804-eaeae900-1d68-11eb-9100-f8d786061ea6.png)

**Comment by artoh** [comment]
Tositetunnisteen 14 / 20 -merkinnässä 20 tarkoittaa tilikautta 2020
Ohjelma jättää sen monesti tulostamatta silloin kuin sekaantumisen vaaraa eri tilikausien välillä ei ole

**Comment by juusoautiosalo** [comment]
Aivan, pahoittelut ylimääräisestä vaivasta ja kiitos erinomaisesta ohjelmasta!
