### ISSUE TITLE
Muu-tositteessa mahdollisuus nettokirjaukseen bruttosummalla

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#793]
Esimerkiksi b-näppäimen evenfiltteröinti niin, että se muuttaa bruttosumman nettosummaksi. Samalla voisi filtteröidä jonkin näppäimen debet <-> kredit -muunnokseen

**Comment by artoh** [comment]
Tähtinäppäin alv-sarakkeessa tekee muuntaa bruton netoksi

**Comment by helihyv** [comment]
Pyöristys aiheuttaa kokonaisumman muuttumisen sentillä esim. 100 € bruttosummalla,
