### ISSUE TITLE
"Yleinen" 2 kertaa "raportin muoto" -valikossa yhdistyksen taseessa

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#797]
Samoin yhdistyksen  tuloslaskelmassa ja budjettivertailussa ainoa vaihtoehto 2 kertaa raportin muoto -valinnassa

**Comment by artoh** [comment]
Onko raportti mahdollisesti päivitetty ensimmäisten versioiden jälkeen? Jossain Kitsaan ensimmäisistä versioista oli muotovalinnan muotokoodissa kirjainkoko-ongelma (tase/Yleinen) kun pitäisi olla tase/yleinen ...
