### ISSUE TITLE
Siirto-tositteiden kohdennus

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#799]
Siirto-tositteiden kohdennus ei tallentunut

**Comment by artoh** [comment]
Ongelmia tase-eräkohdennuksen kanssa (ei säily vaan liittää tositteen itseensä!)

**Comment by artoh** [comment]
Debetin tase-erän hakemisessa oli virhe

**Comment by helihyv** [comment]
Pilvessä tositteen summaksi tallentui oikein 100 €, mutta tase-erän summana näkyi 0,0 €

**Comment by ssalonen** [comment]
Onko tämä bugi vielä auki? Tila githubissa on avoin mutta "4 - Done" tagi löytyy myös.

Jos olen ymmärtänyt oikein, Siirto-tyyppisille tositteille ei voi tallentaa kohdennusta. Kohdennus valintaa ei edes ole käyttöliittymässä! Edes "Muu" tyyppisenä tositteena ei kohdistusta ole mahdollista syöttää. Onko kyseessä tämä sama bugi vai haluatteko, että teen uuden bugin tästä?
