### ISSUE TITLE
Avoimen Kirjanpidon "Sulkeminen"

### ISSUE THREAD

**Issue by NikoGrano** [artoh/kitupiikki#801]
Ominaisuus, joka mahdollistaa kirjanpidon sulkemisen, mutta ohjelman päälle jättämisen.

**Comment by artoh** [comment]
Olisi helppo toteuttaa, mutta ikkuna on jo niin täynnä erilaisia nappuloita ettei oikein raatsisi laittaa yhtä lisää (en keksi tuolle toiminnolle oikein mitään erityistä tarvetta)

**Comment by NikoGrano** [comment]
Sinänsä olen eri mieltä, mutta ymmärrän näkökulmasi. Vaihtoehtona tälle voisi olla myös näppäinyhdistelmä.
![image](https://user-images.githubusercontent.com/4658966/101775080-a1c04e80-3af7-11eb-8f77-44c51a9f5138.png)

Esimerkkitapauksia tästä on, kun kirjanpitoa pidetään erillisillä asemilla ja niitä pitää irroitella ja kytkeä, mutta ei haluaisi sulkea itse sovellusta. Toki, sovelluksen sulkemisella tämä nyt toimii ja sillä on menty.

**Comment by artoh** [comment]
Vastaavaan pääsee luomalla ylimääräisen kirjanpidon ja aktivoimalla sen kun haluaa irroittaa asemat ;)

**Comment by NikoGrano** [comment]
Ai hemmetti kun oon tyhmä... No näin tehdään 👍
