### ISSUE TITLE
Y-tunnuksella voidaan hakea entinen osoite

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#810]
YTJ:stä haettaessa (kumppani sekä kirjanpidon aloitus) haetaan ensimmäinen API:n antama osoite; jos osoitemuutoksia saattaa tämä olla vanhentunut

**Comment by helihyv** [comment]
Osoitteen haku toimii. Kirjanpitoa aloitettaessa ei kuitenkaan enää saada haetuksi kotipaikkaa.
