### ISSUE TITLE
Kysymys: Tilikauden tuonti

### ISSUE THREAD

**Issue by AkiTuomaala** [artoh/kitupiikki#814]
En löytänyt mistään vastaavaa.. Eli jos on esimerkiksi harjoituksena tehnyt yhden tilikauden valmiiksi oikealla aineistolla ja haluaisi tämän tuoda ylläpidettävään yhtenä tilikausista.

**Comment by artoh** [comment]
Tositteiden, vientien ja laskurivien lisäksi tässä pitäisi tuoda asiakas/toimittajarekisterin porukkaa (ja huolehtia näiden tietojen eheydestä), tuotteita yms. ja huolehtia siitä, että tilikartat, kohdennukset ynnä muut kirjanpidon valinnat ovat yhteensopivia.. Todennäköisesti liian iso homma hyötyihin nähden.
