### ISSUE TITLE
Kirjanpidon poisto luettelosta

### ISSUE THREAD

**Issue by jkarppinen** [artoh/kitupiikki#818]
"Poista luettelosta" -napilla ei ole vaikutusta luetteloon. Poistettava kirjanpito on tuotu Kitsaaseen .kitupiikki-filestä.

![3kBaCS04yL](https://user-images.githubusercontent.com/8080353/101959615-5482d080-3c0e-11eb-9e01-fd3215cca8ca.gif)

Versio: Kitsas 2.1.1

**Comment by artoh** [comment]
Jännä. 
En saa tuotettua tuota virhetilannetta vaan itseltäni ne häviävät siivosti luettelosta... Yritetään saada selkoa.
