### ISSUE TITLE
Raporttimallin kopioiminen uuden pohjaksi

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#819]

**Comment by helihyv** [comment]
Jos kopio raporttimallin, tallentaa sen ja valitsee toisen raporrtimallin, ei kopioitua enää näytetä valikossa. Ohjelman käynnistäminen uudelleen tuo sen takaisin.

**Comment by helihyv** [comment]
Raportin nimike-dialogin ohje-napista ei tapahdu mitään.
