### ISSUE TITLE
Elinkeinoelämän ruotsinkielinen tilikartta

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#824]
Sisältää myös ruotsinkielisen tilinpäätöksen

**Comment by helihyv** [comment]
1727 "Siirtyvät" kääntämättä
2615 "Muut pitkäaikaiset joukkovelkakirjalainat" kääntämättä
3000 "Myynti" kääntämättä
Otsikko Henkilöstökulut, vaikka Personalkostnader on myös. PErsonalkostnader alla Löner och arvoden ilman tilejä  ja Henkilästökulut alla ainakin Arbetstagarnas löner och arvodfen, jonka alla tilit.
8450 "Kirjat ja lehdet" kääntämättä
8310 "Patentit" kääntämättä

**Comment by helihyv** [comment]
1727, 2615 ja 8310 korjattu.
3000 ja otsikko oikein uudessa kirjanpidossa
Uudessa kirjanpidossa omat tili kirjoille ja lehdille, niiden käännökset oikein
