### ISSUE TITLE
Erittelemättömät tase-erät täydessä tase-erittelyssä

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#826]
Jos tase-erittelyssä on valittu täysi tase-erittely, niin tase-erittely ei näytä niitä kirjauksia, joille valittu Ei tase-erää (myös saldo tulee väärin)

**Comment by artoh** [comment]
Tämä vaatii päivityksen myös palvelinpuolella

**Comment by anttipalsola** [comment]
Jostain syystä (ilmeisestikin päivitettäessä Kitupiikistä Kitsaaseen) tase-erittelyn tilille, jonka saldon olisi pitänyt olla 0, ilmestyi edelliseltä tilikaudelta peräisin olevia tase-eriä ja saman verran vastakkaismerkkisiä erittelemättömiä eriä. Saldo on siis edelleen oikein (0), mutta tase-erittelyssä näkyy siis turhia eriä.

Yritin korjata ongelmaa tekemällä nollakirjauksen, jonka avulla saan kyllä haamutase-erät pois, mutta erittelemättömiä en saa sillä nollattua.
