### ISSUE TITLE
Alv-lukitun tositteen lisätiedot ja liitteet muokattavissa

### ISSUE THREAD

**Issue by AkiTuomaala** [artoh/kitupiikki#829]
Onko jotenkin mahdollista aukaista edellistä tilikautta, niin että voisi lisätä liitteen tositteeseen?

**Comment by artoh** [comment]
Tilikauden voi avata (Tilikaudet > Muokkaa), mutta jos arvonlisäveroilmoitus on annettu, ei alvillisia tositteita pääse muokkaamaan.
Tähän on toivottu muutosta, että joitain muokkauksia (esim. muistiinpanot) voisi tehdä vielä alv-ilmoituksen jälkeenkin.

**Comment by artoh** [comment]
Lisätään ominaisuus: Alv-lukittuun tositteessa voi muokata liitteitä sekä lisätietoja
