### ISSUE TITLE
ALV% bruttokirjauksissa

### ISSUE THREAD

**Issue by hasseb** [artoh/kitupiikki#838]
Jos myyntitilin asetuksissa verolaji on brutto ja alv % 24 ja tilille tekee kirjauksen muu-tositteelle, niin verolajiksi tulee brutto mutta ALV % on tyhjä (0%).

**Comment by artoh** [comment]
En saanut toistettua virhettä

![image](https://user-images.githubusercontent.com/1282146/103457744-9d5c0f80-4d0a-11eb-9948-78ce8791a405.png)

**Comment by hasseb** [comment]
oli näköjään joitan hämminkiä tilin asetuksissa ja ei ollut veroprosentti mennyt oikeaan paikkaan perille. kun veroprosentit laittoi uudestaan, niin alkoi toimimaan. en tiedä mikä oli, mutta tämän voi mun puolesta sulkea.
