### ISSUE TITLE
Edustuskulut laskettu väärin tuloslaskelmassa

### ISSUE THREAD

**Issue by NikoGrano** [artoh/kitupiikki#839]
Edustuskulut on Oy tilikartalla 7950 - 7990. Nämä on puoliksi vähennyskelpoisia.

Tilinpäätöksen tuloslaskelmassa nämä on kumminkin vähennettynä kokonaan.

**Comment by artoh** [comment]
Tuloslaskelmaan nämä tulevat kokonaan (kuten myös verotuksessa kokonaan
vähennyskelvottomat erät ja verottomat tulot) --> näin tilikauden tulos
myös siirtyy oikein taseeseen.

Tilityyppivalinta vaikuttaa tilinpäätöksen tuloverolaskelmaan, jossa
huomioidaan osittainen vähennyskelpoisuus.


la 2. tammik. 2021 klo 17.00 Niko Granö (notifications@github.com)
kirjoitti:
