### ISSUE TITLE
Moni PDF-tiedosto muuttuu mustaksi

### ISSUE THREAD

**Issue by asmolero** [artoh/kitupiikki#842]
Kun raahaan PDF-tiedostoja tositteeseen, tiedoston tausta muuttuu mustaksi eikä mitään voi lukea.

![img-2021-01-06-011748](https://user-images.githubusercontent.com/1392080/103710212-61e07000-4fac-11eb-9dd7-47543fb9d81e.png)

Samaa jos laitan "muuta mustavalkoiseksi" -asetus päälle.

![img-2021-01-06-012407](https://user-images.githubusercontent.com/1392080/103710556-33af6000-4fad-11eb-88d1-cdd4f74c9bca.png)

Kun tallennan tositteen ja avaan liitteen se on muuttunut BMP-tiedostoksi, jossa teksti on ehdottomasti hävitty.

Arch Linux
Kitsas 2.1.1
Qt 5.15.2
poppler-qt5 20.12.1

**Comment by asmolero** [comment]
Ongelma jatkuu kun luon uuden kirjanpidon.

**Comment by artoh** [comment]
Onko kyseessä Kitsaan virallinen AppImage vai oma käännös?
Jotain tällaista voisi tapahtua, jos järjestelmässä olisi QImage plugin pdf:lle (en tiedä, onko sellaista edes olemassa), mutta silloinkin lopputuloksena pitäisi olla jpg- eikä pdf-tiedosto

**Comment by asmolero** [comment]
Oli oma käännös. Yritän joskus selvittää, mistä ongelma tulee.

AppImage-sovelluksessa toimii, käytän sitä sillä välin.
