### ISSUE TITLE
Tilikausien korjaaminen (muokkaaminen)

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#845]
Korvataan joitain päivämäärärajauksia varoituksilla / virheilmoituksilla tallennusvaiheessa
- viimeisen kauden lopun muuttaminen niin että kirjauksia tämän jälkeen
- ensimmäisen kauden alun muuttaminen
- pitäisi antaa mahdollisuus määrittää ensimmäinen kausi tilinavaukseksi?

**Comment by helihyv** [comment]
Tilikauden alun muuttaminen ei tallennu pilvessä eikä paikallisesti.

**Comment by helihyv** [comment]
Ensimmäistä tilikautta ei voi muuttaa tlinavaukseksi, valinta ei ole aktiivinen,
