### ISSUE TITLE
Projektiraportti tositteineen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#848]
Mahdollisuus tulostaa projektiraportti (päiväkirjan ote) jonka mukana kaikki otteeseen liittyvät tositteet. Tehtäisiin hyödyntämällä kirjanpitoaineiston tulostamista.

**Comment by helihyv** [comment]
Tositteiden tietoja päällekkäin ensimmäisen sivun yläreunassa

**Comment by helihyv** [comment]
Raportti ei avaudu esikatselunapista (Windows). Raporttia luodaan -ilmoitus tulee ja poistuu,

**Comment by helihyv** [comment]
Tililuetteleoa ei tulostu, ellei raporttejakin tulosteta.

**Comment by helihyv** [comment]
Raportti ei useimmiten avaudu esikatselunapista, satunnaisesti avautuu.
