### ISSUE TITLE
Alv-ilmoitus:  negatiivisten bruttokirjausten oikaisut

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#860]

**Comment by helihyv** [comment]
Negatiivistent ostokirjausten oikaisur yhä miinusmerkkisinä eivätkä siksi näy

     {
            "alvkoodi": 22,
            "alvprosentti": 14,
            "kredit": -7.61,
            "pvm": "2020-03-31",
            "selite": "Brutto-ostojen oikaisu 4000 Ostot BRUTTO −62,00, NETTO −54,39",
            "tili": 4000,
            "tyyppi": 91091
        },
        {
            "alvkoodi": 222,
            "alvprosentti": 14,
            "debet": -7.61,
            "pvm": "2020-03-31",
            "selite": "Brutto-ostojen oikaisu 4000 Ostot BRUTTO −62,00, NETTO −54,39",
            "tili": 1763,
            "tyyppi": 91091
        },

Myyntikirjauksissa toimii.
