### ISSUE TITLE
Kitsas kaatuu kun tekee Alv-tilityksen kesken vuotta alkavalle tilikaudelle oy:lle ilman toimintaa

### ISSUE THREAD

**Issue by cxcorp** [artoh/kitupiikki#861]
Bugintoistoaskeleet:
- Luo uusi todellinen kirjanpito osakeyhtiölle "suppea, ei varastoa" -tilikartalla, jonka tilikausi on esim. 15.12.2020 - 31.12.2021, laita [x] Toiminta alkaa vasta tästä tilikaudesta (ei tilinavausta)
- Mene ALV-täbiin
- Valitse Verokausi: Vuosi
- Laita alkupvm 1.1.2020 ja loppupvm 31.12.2020
- Paina Tee alv-tiliys
- Ohjelma kaatuu ilman virheviestiä

Tarkoituksena on siis merkitä Alv-tilitys viime vuodelle uudelle yritykselle, jolla ei ole ollut vielä toimintaa.

Debuggerilla saan Windows-virhekoodiksi 0xc0000094 eli kokonaisluvun nollalla jako, joka tulee osoitteesta 0xC9F28B Kitsas 2.2:n installerilla asennetulla .exe:llä. Sama bugi tapahtuu linux- ja macOS-jakelulla. Call stack on suunnilleen 0xC9F1F0 <- 0xEFCDD1, joista 0xC9F1F0 taitaa olla qDebugin text streamin `<<`-operaattori tai joku matematiikka-apuri ja 0xEFCDD1 taitaa olla:

https://github.com/artoh/kitupiikki/blob/c9eea46d45ebc04786d441e964664bfd5dab0526/kitsas/alv/alvlaskelma.cpp#L694-L698

Jos pitäisi arvata, `suhteutuskuukaudet_` on varmaan 0 joten tulee nollalla jako.

ALV-tilityksen saa tehtyä, jos vaihtaa verokaudeksi kuukauden ja laittaa ALV-ilmoituksen 1.12.2020 - 31.12.2020 ja painaa Tee alv-tilitys, jonka jälkeen sitten voi vaihtaa verokauden vuodeksi.

Testi-sqlitekanta: [test.zip](https://github.com/artoh/kitupiikki/files/5821634/test.zip)

**Comment by artoh** [comment]
Virhe on leivottu sisään verottajan ohjeisiin eli ym. tilanteessa päädytään verottajan ohjeita seuraamalla nollalla jakamiseen:

Suhteuttaminen tehdään kertomalla huojennukseen oikeuttava liikevaihto luvulla 12 ja jakamalla näin saatu luku tilikauden täysien kalenterikuukausien lukumäärällä. Vajaita kalenterikuukausia ei siis lasketa mukaan liikevaihtoa suhteutettaessa.

Tässä voitaneen matematiikan suojaamiseksi merkitä yksi suhteutuskuukausi jotta päästään laskemaan alv:n alarajahuojennus?
