### ISSUE TITLE
Tiliotteen muokkaaminen hävittää ALV viennit

### ISSUE THREAD

**Issue by NikoGrano** [artoh/kitupiikki#863]
Esimerkki kirjauksista ennen tiliotteen muokkaamista.
![image](https://user-images.githubusercontent.com/4658966/105010253-2631b580-5a44-11eb-86a2-1eb552aad697.png)

Tämän jälkeen kirjaan uuden rivin ja viennit näyttää tältä:

![image](https://user-images.githubusercontent.com/4658966/105010595-99d3c280-5a44-11eb-8cf6-a0dcf629141f.png)

Kun tämän tästä menee tallentamaan ja katsoo ALV raporttia, sieltä puuttuu kaikki kirjaukset näille aikaisemmille tiliotteen riveille.

Ja tuo tiliote näyttää tältä:
![image](https://user-images.githubusercontent.com/4658966/105011000-15ce0a80-5a45-11eb-939f-147d070981e3.png)
(Tuo 31€ tuolla ns testikirjauksena.)

**Comment by NikoGrano** [comment]
@artoh Testailin tätä 2.3-beta win versiolla ja sama toistuu vieläkin uudelleen.

**Comment by artoh** [comment]
@NikoGrano Testasithan tätä tetemällä kokonaan uuden tiliotteen? Bugi oli tiliotteen metatietojen tallentumisessa (ts. aiemmilla versioilla tehdyissä tiliotteissa ei ole niitä metatietoja mukana, joilla muokkaamisen yhteydessä saadaan nuo lisärivit luotua).

**Comment by NikoGrano** [comment]
Enhän tietenkään. Kiitän infosta!
