### ISSUE TITLE
Siirto-tositeapuriin napin taakse mahdollisuus yksittäisen laskun poimimiseen ja maksamiseen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#883]

**Comment by helihyv** [comment]
Jos napista valitaan lasku ja nappia painetaan uduestaan ja valitaan uusi lasku, näkyy uuden laskun tiedot, mutta tallentuu vanhan laskun tiedot.

**Comment by helihyv** [comment]
Myös asiakkaan/toimittajan tiedot voisi tuoda.
