### ISSUE TITLE
Tilinavaus lisättävissä jälkeenpäin

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#885]

**Comment by artoh** [comment]
Tilinavauksen käsittelyssä tositetta ei enää käsitellä id 1:n perusteella, vaan tositetyypin 9010 (Tilinavaus). Näin ollen tilinavaus on lisättävissä myös myöhemmin.

**Comment by artoh** [comment]
Mahdollisuus tilikauden lisäämiseen myös alkuun

**Comment by helihyv** [comment]
Jos lisätään alkuun tilinavauskausi ja poistetaan se, ei alkuun voi enää lisätä uutta tilikautta.

**Comment by helihyv** [comment]
Alkuun lisättävä tilikausi on lukittu, vaikka ei olisi tilinavaus.
