### ISSUE TITLE
Kaikkien tilikausien poistaminen estettävä

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#905]

**Comment by helihyv** [comment]
Kaikki tilikaudet on yhä mahdollista poistaa sekä pilvessä että paikallisesti.

**Comment by helihyv** [comment]
Pilvessä on yhä mahdollista poistaa kaikki tilikaudet, jos viimeinen tilikausi on ollut lukittu ja poistamisen tekee heti lukituksen avaamisen jälkeen poistumatta välillä tilikauden muokkausdialogista,
