### ISSUE TITLE
Sähköpostissa vailinnaisuutta

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#914]
Lähetin Kitsaksesta sähköpostilaskuja ja jostakin syystä vastaanottajan tietokoneella sähköpostin liitteenä on pdf:t normaalisti, mutta puhelimella tai tabletilla sähköpostissa näkyy kyllä klemmari eli liitetiedoston merkki, mutta itse liitetiedostoja ei näy missään. Kitsaksesta minulla on käytössäni uusin versio 2.3.

Asiakas ilmoitti tästä ja tein testilaskun itselleni ja sama ongelma. Kitsas on MacBook Prossa ja puhelimena minulla on iPhone 11 Pro. Asiakkaan laitteista en tiedä.

Lisäksi Macin sähköpostissa (Mail) laskun lähettäjänä näkyy (Ei lähettäjää), mutta puhelimessa näkyy ihan oikein Kitsaksen asetusten mukainen Green Circle.

**Comment by artoh** [comment]
Mahdollisesti tuo laskun lähettäjän puuttuminen voi olla Macin ongelma

**Comment by atfos** [comment]
Mikä on tuo Green Circle?

**Comment by petriaarnio** [comment]
Mikä on tuo Green Circle?

**Comment by artoh** [comment]
Helsinkiläinen matkailuautovuokraamo
