### ISSUE TITLE
Luottokorttiostot maksuperusteisella alvilla

### ISSUE THREAD

**Issue by NikoGrano** [artoh/kitupiikki#917]
Kun käytössä on maksuperusteinen ALV, tulee luottokorttiostojen viennit näyttämään seuraavalta:

![image](https://user-images.githubusercontent.com/4658966/110300835-12481000-8000-11eb-9905-9f3789322292.png)

![image](https://user-images.githubusercontent.com/4658966/110300507-9c43a900-7fff-11eb-9e62-0f1bb4f3f1f3.png)

Tässä on yksi pieni ongelma, kun luottokorttivelat kuitataan maksetuiksi, tuo arvolisäverosaaminen jää vieläkin tilille 17631 (Maksuperusteinen arvolisäverosaaminen). Tämä vaatii erikseen kirjauksen, joka siirtää arvolisäverosaamiset oikealle tilille.

Pitäisikö tässä kohtaa sallia maksun tekeminen ei maksuperusteisella ALV tyypillä, vai teenkö jotain väärin?

**Comment by artoh** [comment]
Ongelmahan tässä on, että luottokorttiostoja ei ole eritelty niin että ohjelma pystyisi seuraamaan tämän nimenomaisen erän maksamista. Täytynee muuttaa niin, että luottokorttiostotkin menevät käteisostojen tavoin heti alv-käsittelyyn, vaikka oikein tarkasti verottajan ohjeita tihraamalla pitäisi kai odottaa että myös luottokorttimaksu on maksettu tililtä.

**Comment by NikoGrano** [comment]
Dirty fix, mutta hyväksyttävä näin alkuun. Luulen, että tästä pitäisi varmaan pidemmän ajan päälle tehdä korjaus, jossa noita seurattaisiin. Työmäärää onkin sitten vähän kysymysmerkki näin pienen ominaisuuden vuoksi.

Onhan tuo luottokorttiostot tili kumminkin ostovelkaa, eikä ostovelkaa pitäisi maksuperusteisessa pystyä vähentämään ennen kuin se on maksettu kokonaisuudessaan. Eli perjaatteessa "won't fix" ja kirjaus tulisi tehdän käsin, jotta kirjanpito pysyy pilkulleen lainmukaisena,. Tässä sitten herääkin kysymys, että kuinkahan moni käyttäjä osaa katsoa tämän oikein ja tehdä lisäkirjauksen?
