### ISSUE TITLE
Verkkolaskuasetuksiin varoitus jos yhteystiedot puutteelliset

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#918]

**Comment by helihyv** [comment]
Varoitus näkyy, mutta samalla näkyy myös kehoitus kirjautua Kitsas-tunnuksilla, vaikka olisi jo kirjautuneena. (Jos yhteystiedot ovat kunnossa, kirjautumiskehotus näkyy vain jos ei ole kirjautunut.)
