### ISSUE TITLE
Pääkirjaan tulostuu väärä tilikauden tulos

### ISSUE THREAD

**Issue by anttipalsola** [artoh/kitupiikki#927]
Jostain syystä Kitsas 2.3 tulostaa pääkirjaan (PDF) tilikauden tuloksen (tili 2460) väärin: Oikea tulos olisi nelinumeroisen summan ylijäämäinen, mutta tuloslaskelmassa tulokseksi on merkitty −60,00 euroa. Tuloslaskelmaan, taseeseen ja tase-erittelyyn summa tulostuu oikein.

Edellä oleva koskee siis tulosttettavaa tai PDF:ksi tallennettavaa pääkirjaa. HTML-muotista pääkirjaa en ole tältä osin vielä tarkastanut.

**Comment by artoh** [comment]
Onkohan summa oikein myös Aloita-näytössä?

**Comment by anttipalsola** [comment]
Kyllä, summa on oikein myös aloitusnäytössä.

**Comment by anttipalsola** [comment]
Virhe esiintyy myös HTML-muotoisessa arkistossa.

**Comment by PetriRa** [comment]
Ethän ole kirjannut jotain tuolle tilille itse. Pääkirjaanhan tilikauden tuloksen ei pitäisi tulostua lainkaan.

**Comment by anttipalsola** [comment]
Ainakaan tarkoituksellisesti en ole kirjannut tilille 2460 mitään. Vahinkokirjaus on tietysti aina mahdollinen, mutta sen kai pitäisi näkyä pää- ja päiväkirjassa. Nyt päiväkirjasta (PDF & HTML tarkistettu) ei löydy hakusanalla 2460 mitään ja pääkirjassa on vain tuo saldo mutta ei kirjauksia. Lisäksi etsin tiliä myös käyttöliittymän Selaa → Viennit -toiminnolla, mutta silläkään ei löytynyt.

Virhe on syntynyt nimenomaan Kitsaalla tehdyn tilikauden 2020 aikana tai Kitupiikki → Kitsas -konversiossa. Kitupiikillä tehdyssä vuoden 2019 kirjanpidossa virhettä ei näy.

**Comment by anttipalsola** [comment]
Sain selvitettyä tätä lisää, kun otin kolmelta vuodelta pääkirjan vuoden ensimmäiseltä päivältä (siis esim. 1.1.2021–1.1.2021).

- Virhe syntyy aina vuoden/tilikauden ensimmäisenä päivänä (1.1.).
- Virheen suuruus on aina laskettavissa yhteen- ja tai vähennyslaskuna päivämäärälle 1.1. tehdyistä tasetilien kirjauksista.

**Comment by anttipalsola** [comment]
Testailin vähän lisää. Näyttäisi siltä, että 2460-tilin saldo kunakin tilikautena on koko tilikauden ajan kyseisen tilikauden ensimmäisenä päivänä (1.1.) tasetileille tehtyjen kirjausten yhteenlaskettu debet − kredit. Virhettä ei synny, jos päivämäärälle 1.1. ei tehdä kirjauksia. Virhe ei myöskään näyttäisi periytyvän tilikaudelta toiselle, vaan saldoon vaikuttavat vain kyseisen tilikauden ensimmäisen päivän kirjaukset.

Ongelma toistuu omalta osaltani kahdella eri kirjanpitovelvollisella:
- Ensimmäisessä on otettu Kitupiikki käyttöön tilikauden 2019 alussa ja konvertoitu Kitsaaseen tilikauden 2020 alussa. Jos luon Kitsaalla tilikauden 2019 pääkirjan, ongelma esiintyy nyt siinäkin, vaikka se ei esiintynyt aikanaan Kitupiikillä luodussa pääkirjassa. Lisäksi ongelma esiintyy myös tilikausilla 2020 ja 2021.
- Toisessa on otettu Kitsas käyttöön tilikauden 2020 alussa. (Kitupiikki → Kitsas -konversiota ei siis ole tehty.) Tässä ongelma esiintyy vian tilikaudella 2021, mutta tämä johtunee siitä, ettei 1.1.2020 ole yhtään kirjausta. (Tilikausi 2020 on jo suljettu ja tilinpäätös vahvistettu, joten en pysty sitä enää testikirjauksilla testaamaan.)

Toisin kuin aiemmassa kommentissani (20.3.2021) epäilin, virhe ei siis näyttäisikään liittyvän Kitupiikki → Kitsas -konversioon, vaan tilikauden ensimmäisen päivän kirjauksiin. Tarkalleen ottaen en tosin tiedä, liittyykö ongelma kalenterivuoden vai tilikauden ensimmäiseen päivään, koska ne ovat minun tapauksessani sama asia. (Tilikausi on kalenterivuosi.)

**Comment by anttipalsola** [comment]
@PetriRa Pystykö testaamaan, toistuuko ongelma sinulla? Pitäisi siis riittää, että tekee tasetileille vaikuttavia kirjauksia 1.1. Tämän jälkeen tilin 2460 saldon pitäisi olla pääkirjassa kyseisten kirjausten tasetilien debet − kredit.

Lisäykseksi vielä, että molemmat edellisessä kommentissani mainitut kirjanpitovelvolliset ovat yhdistyksiä. En tiedä, toistuuko ongelma muilla yritysmuodoilla.

**Comment by artoh** [comment]
Ongelma liittyy siihen, että ohjelma hakee tilien alkusaldoja pääkirjaan samalla menettelyllä mitä näytetään aloitussivulla (mutta toisella päivämäärärajauksella), ja tämä tilikauden tulokseen otetaan mukaan myös tilikauden ensimmäinen päivämäärä.

Korjaus tulee versioon 3, jossa tilikauden tulokselle ei lasketa lainkaan alkusaldoa (tämähän poikkeaa sikäli muista taseen tileistä ettei tämä säilytä saldoaan tilikaudesta toiseen). Todellisuudessa ohjelma ei koskaan kirjaa näille tileille mitään, vaan kaikki summat ovat laskennallisia.

**Comment by anttipalsola** [comment]
@artoh Hienoa, jos ongelma on korjaantumassa, kiitos! Ja tämän olinkin jo toki huomannut, että virhe ei vaikuta muuhun kuin pääkirjassa näkyvään ko. tilin saldoon.
