### ISSUE TITLE
Epälooginen kysymyksenasettelu poistuttaessa tositteesta tallentamatta sitä

### ISSUE THREAD

**Issue by anttipalsola** [artoh/kitupiikki#939]
### Ympäristö

Ubuntu 20.04.2
Kitsas 2.3

### Ongelman toistaminen

1. Muokkaa tositetta.
2. Siirry pois tositteesta tallentamatta sitä.

### Odotettu tulos

Avautuu ikkuna, jossa on esimerkiksi teksti:

> Nykyistä kirjausta on muokattu. Haluatko tallentaa tekemäsi muutokset?
> * Kyllä
> * Ei
> * Peruuta

tai:

> Nykyistä kirjausta on muokattu. Haluatko tallentaa tekemäsi muutokset?
> * Tallenna
> * Älä tallenna
> * Palaa tositteeseen

### Todellinen tulos

Avautuu ikkuna, jossa on teksti:

> Nykyistä kirjausta on muokattu. Poistutko sivulta tallentamatta tekemiäsi muutoksia?
> * Kyllä
> * Ei

Tämä on ainakin oman kokemukseni perusteella epäloogista: Yleensä tämänkaltaisiin ikkunoihin "Kyllä"-vastaus tarkoittaa aina muutosten tallentamista ja "Ei" niiden hävittämättä. Nyt logiikka on jokseenkin päinvastainen. Tämän perusteella olen ainakin itse pari kerta klikannut vanhasta tottumuksesta "Kyllä" ja näin menettänyt tekemäni muutokset.

**Comment by artoh** [comment]
Vaihdetaan toinen napeista. Tallennusvaihtoehto on sikäli monitulkintainen, että tilanteesta riippuen tositteen voi tallentaa luonnoksena ja/tai valmiina.

![image](https://user-images.githubusercontent.com/1282146/114905891-23b3e180-9e22-11eb-90f7-a4450a1d1f9e.png)
