### ISSUE TITLE
Pankkikorttiostojen käsittelyn automatisointia

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#951]
Mun kirjanpitoasiakkaat ostelee aika paljon pankkikortilla, tekevät esim keikkahommaa ja tankkaavat automaatista.

Kirjailen bensakuitit ensin (esim nyt perjantaina on käyty Teboililla, 16.4.2021, Maksutapa Pankkitili), ja sitten tiliotteen myöhemmin.

Näiden kohdistumisessa toisiinsa on aina ongelma.

Ilmeisesti Kitsas tunnistaa tiliotetta kirjattaessa tapahtuman samaksi, jos sekä summa, että päivämäärä ovat samoja? Ainakin tuntuu tunnistavan, jos tuo bensakuitti onkin alunperin kirjattu sille päivälle, joka tiliotteella näkyy maksupäivänä.

Kuitenkin pankkikorttiostojen maksupäivänä tiliotteella on käytännössä lähes aina ostopäivää seuraava pankkipäivä. Eli tässä tapauksessa maksupäivänä tiliotteella onkin maanantai 19.4.2021.

Viestikentässä on kyllä todellinen ostopäivä näkyvissä, esim OP:n tyylillä vvkkpp (OSTOPVM 210416), tai Oma Säästöpankilla pp.kk.vvvv (OSTOPVM 16.04.2021). Tuon viestikentän ostopvm:n hyödyntäminen lienee hankalaa, monista variaatioista johtuen.

Voisikohan Kitsaalle antaa hieman toleranssia päivämääriin tiliotetta kirjattaessa, eli tapahtumat tunnistettaisiin samaksi, jos summa täsmää, ja tiliotteella maksupäivä on sama, tai seuraava pankkipäivä, kuin on ollut todellinen ostopäivä?

Kuitteja kirjattaessa luonnollisesti tulee käytettyä sitä päivää, joka siinä lukee. Ja nyt kun nämä ei kohdistu toisiinsa, niin aiheutuu turhaa työtä rivejä poistellessa, tai tulee vahingossa kirjattua tiliotteella uudestaan kulutilille.

**Comment by artoh** [comment]
- Tilitapahtumia tuodessa otetaan siivottaessa huomioon myös Ostopvm-kenttä
- Pankkikortti-maksutapa, joka ohjaa pankkikorttisaataviin ja joille voidaan myös kaikki pankkikorttimaksut tiliöidä (käyttökelpoinen etenkin pankkiyhteydellä tuotaessa)

**Comment by helihyv** [comment]
Pankkikorttisaamiset on yritystilikartassa laajuudella "tavallinen", yhdistys- ja asunto oy tilikartoissa "tavallinen, ei palkkoja".  Pitäisi olla suppea, koska sille on valmiiksi maksutapa.
