### ISSUE TITLE
Helpompi useamman liitteen lisääminen

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#960]
Uusi tosite, voin vetää Kitsaaseen ruudun yläosaan ensin XML’n ja sitten PDF’n perään. Tai vaikka palkka.fi -CSV/TXT’n, ja sitten PDF’n perään.

 

Mutta jos ensin vedän PDF’n, en voi enää vetää toista PDF’ää, vaan tällöin on ekan jälkeen mentävä Liitteet-välilehdelle, johon voi sitten lisäillä muita PDF’iä.

 

Onko tähän joku järkevä syy, miksi toiminto ei ole aina tuon ensimmäisen kaltainen?

 

Ei tämä nyt mikään ongelma ole, mutta ylimääräisiä klikkauksia aiheuttava.

 

Toinen liitteisiin liittyvä kummallisuus, xml’t ja csv-muotoiset .txt-tiedostothan on käytännössä puhdasta tekstiä, ja ne näytetään kitsaassa tekstinä. Sitten jos vedän jonkun muun, kissanpieru.txt puhtaan tekstitiedoston, saan herjan ”… ei voi välttämättä näyttää Kitsaalla … sisällyttää arkistoon…jne”.

Tämäkin tuntuu hieman oudolta, eikö tässä kuitenkin komponentti täydy olla jo olemassa txt tiedostojen näyttöön? Näitä vaan olisi tarve lisäillä.

**Comment by helihyv** [comment]
Useamman PDF:n lisääminen vetämällä onnistuu.

Sama varoitus txt-tiedostoista kuin ennenkin, tarkoituksella.
