### ISSUE TITLE
Laskujen päivämäärät ja eräpäivät laskua muokattaessa

### ISSUE THREAD

**Issue by artoh** [artoh/kitupiikki#963]
Laskua muokattaessa laskun päivämäärä, maksuaika ja eräpäivä eivät ole aina oikein.
Lisäksi pitäisi implementoida asiakaskohtaisen maksuajan toteuttaminen (olisiko lisättäessä asiakas laskuun, jossa ei aiemmin ole ollut asiakasta?)

**Comment by helihyv** [comment]
Laskun eräpäivän muuttumisessa laskun päivän tai suorituspäivän mukaan yhä pieniä heittoja
