### ISSUE TITLE
Tilinpäätöksen laatimisperusteissa ei mainintaa PMA-säännöstöstä

### ISSUE THREAD

**Issue by bartosz-r-o-l-l** [artoh/kitupiikki#985]
Kitsas 2.3 tilinpäätös-toiminnallisuus eroaa tilinpäätöksen laatimisperusteiden osalta Kitupiikkiin nähden: Kitupiikissä tilinpäätöstekstiin tuli asoy tapauksessamme maininta mikroyrityssäännöstön noudattamisesta, mutta tuota tekstiä ei tule Kitsaalla tilinpäätöstä luotaessa vaikka yrityksen pitäisi edelleen täyttää mikro-yrityksen määritelmän ja asetuksissa tilinpäätösmalli sisältää vastaavan osion (#MIKRO) PMA:n soveltamisesta.
Yrityksen toiminnan laajuus ei kuitenkaan ole viime vuodesta muuttunut.
Onkohan kyseessä bugi?

---

Kitupiikin sisällyttämä tilinpäätöksen laatimisperuste-teksti:

### Tilinpäätöksen laatimisperusteet

Tilinpäätöksenlaatimisessaonnoudatettupien- jamikroyrityksentilinpäätöksessä esitettävistä tiedoistaannetunasetuksen(PMA) mikroyrityssäänöstöä.

---

Kitsas 2.3:n laatimisperuste-teksti

### Tilinpäätöksen laatimisperusteet

Asunto-osakeyhtiöstä on annettava täydet liitetiedot

Liitetiedot sisältävät ainakin
1. tilinpäätöksen esittämistapaa koskevat tiedot 2. tilinpäätöksen laatimisperusteet
3. tuloslaskelmaa koskevat liitetiedot
4. tasetta koskevat liitetiedot
5. liitetiedot käypään arvoon merkitsemisestä
6. tuloveroja koskevat tiedot
7. vakuudet, vastuusitoumukset ja taseen ulkopuoliset järjestelyt 8. tiedot tilintarkaastajien palkkioista
9. lähipiiriliiketoimet
10. tiedot henkilöstöstä ja toimielinten jäsenistä
11. omistukset muissa yrityksissä
12. konserniin kuuluvaa kirjanpitovelvollista koskevat tiedot
Lisäksi liitetietona on annettava tiedot sidotuista rahastoista

**Comment by bartosz-r-o-l-l** [comment]
Kitsas sisällyttää laatimisperusteisiin tekstin "Asunto-osakeyhtiöstä on annettava täydet liitetiedot".
Onko viitettä mistä tämä edellytys on peräisin? 🤔 

En tunne kirjanpitosäännöstöä tarkasti, eivätkä alla olevat taida antaa ihan suoraa vastausta kysymykseen, mutta pari aihetta sivuavaa viitettä
* Kirjanpitolautakunnan [yleisohje](https://www.kiinteistolehti.fi/wp-content/uploads/sites/9/2017/06/AsOy_yleisohje-01022017.pdf) asunto-osakeyhtiöiden ja muiden keskinäisten kiinteistöyhtiöiden kirjanpidosta, tilinpäätöksestä ja toimintakertomuksesta 1.2.2017
> 5.3. Lyhennetyn tasekaavan käyttö
>
> PMA 2:4 §:n tai PMA 4:2 §:n mukaisten tasekaavojen käyttö on useimmille asunto-osakeyhtiölle ja
keskinäisille kiinteistöosakeyhtiöille mahdollista, sillä ne ovat yleensä pien- tai mikroyrityksiä.
* Mikrokokoisen asunto-osakeyhtiön mahdollisuudesta valita mikroyrityksen taikka pienyrityksen tilinpäätössäännöstö https://kirjanpitolautakunta.fi/-/mikrokokoisen-asunto-osakeyhtion-mahdollisuudesta-valita-mikroyrityksen-taikka-pienyrityksen-tilinpaatossaannos-1

**Comment by artoh** [comment]
Mitä Tilikaudet-sivu näyttää tilikauden taseeksi ja liikevaihdoksi?
Onko https://ohjeet.kitsas.fi/tilinpaatos/asiakirja/ tilinpäätöstä modostettaessa valittavissa säännöstöksi Mikroyritystä ja onko se valittu?
Nopeasti vaikuttaisi siltä, että ohjelma tulkitsee ettei PMA-säännöstöä voi soveltaa ja tulostaa siksi isommille yrityksille tarkoitetun tekstin.

**Comment by bartosz-r-o-l-l** [comment]
> Mitä Tilikaudet-sivu näyttää tilikauden taseeksi ja liikevaihdoksi?

Taseen loppusumma on alle 500 k€, liikevaihto ~ 2 k€ ja työntekijöitä 0.
Näin ollen mikroyrityksen kriteerien tulisi ymmärtääkseni täyttyä.

> Onko https://ohjeet.kitsas.fi/tilinpaatos/asiakirja/ tilinpäätöstä modostettaessa valittavissa säännöstöksi Mikroyritystä ja onko se valittu?

Avasin uudelleen tilinpäätöstoiminnallisuuden liitetiedot -näkymän, valitsin "Aloita uudelleen", valitsin sovellettavaksi säännöstöksi "mikroyritys". Tämän jälkeen laatimisperusteet -tekstissä on maininta PMA-säännöstön noudattamisesta.
Kun tekstin vielä tallensi sai sen näkymään tilinpäätösluonnoksessa.

Kummallista. Tilinpäätöksen valmistelu on aloitettu jo jokin aika sitten enkä enää muista tarkalleen ottaen olenko valinnut jonkin muun kuin mikroyrityksen valintalistasta. Se tuntuisi kuitenkin epätodennäköiseltä.

Ongelma näyttää kuitenkin ratkenneen yllä olevan vinkkisi avulla!
Kiitoksia! 🙇
